// ---------------------------------------------------------------------------
// Route canonicalization
// ---------------------------------------------------------------------------

const UNKNOWN_API_RATE_LIMIT_PATH = '/api/__unknown__';

export const API_ROUTE_TEMPLATES = [
  '/api/admin/capacity',
  '/api/admin/data-explorer/:id',
  '/api/admin/data-explorer/:id/:id',
  '/api/admin/data-explorer/models',
  '/api/admin/escalation-rules',
  '/api/admin/escalation-rules/:id',
  '/api/admin/external-professionals',
  '/api/admin/external-professionals/:id',
  '/api/admin/external-professionals/:id/communications',
  '/api/admin/external-professionals/:id/patients',
  '/api/admin/facilities',
  '/api/admin/facilities/:id',
  '/api/admin/facilities/:id/contacts',
  '/api/admin/facilities/:id/patients',
  '/api/admin/facilities/:id/units',
  '/api/admin/facilities/:id/units/:id',
  '/api/admin/facilities/:id/visit-batches',
  '/api/admin/facility-standards',
  '/api/admin/flush-metrics',
  '/api/admin/inventory-forecast',
  '/api/admin/master-hub',
  '/api/admin/metrics',
  '/api/admin/operations-insights',
  '/api/admin/organizations',
  '/api/admin/performance-metrics',
  '/api/admin/pharmacist-credentials',
  '/api/admin/pharmacist-credentials/:id',
  '/api/admin/pilot-launch-dossier',
  '/api/admin/pilot-org-audit',
  '/api/admin/pilot-readiness',
  '/api/admin/reject-reason-stats',
  '/api/admin/staff-metrics',
  '/api/admin/uat-feedback',
  '/api/admin/uat-feedback/:id',
  '/api/admin/uat-feedback/summary',
  '/api/admin/webhooks',
  '/api/audit-logs',
  '/api/audit-logs/:id/review',
  '/api/audit-logs/export',
  '/api/auth/:path*',
  '/api/auth/mfa/recovery',
  '/api/auth/password/reset/confirm',
  '/api/auth/password/reset/request',
  '/api/billing-candidates',
  '/api/billing-candidates/:id',
  '/api/billing-candidates/:id/collection',
  '/api/billing-candidates/:id/documents/pdf',
  '/api/billing-candidates/close',
  '/api/billing-candidates/export',
  '/api/visit-billing-candidates',
  '/api/visit-billing-candidates/summary',
  '/api/pharmacy-invoices',
  '/api/pharmacy-invoices/:id',
  '/api/pharmacy-invoices/:id/pdf',
  '/api/pharmacy-operating-hours',
  // Platform operator console (audited break-glass cross-tenant access).
  '/api/platform/tenants',
  '/api/platform/break-glass',
  '/api/platform/break-glass/:id',
  '/api/platform/tenants/:id/data',
  '/api/platform/tenants/:id/audit',
  '/api/billing-evidence/analytics',
  '/api/billing-evidence/check',
  '/api/billing-evidence/stats',
  '/api/billing-rules',
  '/api/billing-rules/:id',
  '/api/business-holidays',
  '/api/business-holidays/:id',
  '/api/care-reports',
  '/api/care-reports/:id',
  '/api/care-reports/:id/finalize',
  '/api/care-reports/:id/pdf',
  '/api/care-reports/:id/print-audit',
  '/api/care-reports/:id/send',
  '/api/care-reports/analytics',
  '/api/care-reports/generate-from-visit',
  '/api/care-reports/reminders',
  '/api/care-reports/today-workspace',
  '/api/cases',
  '/api/cases/:id',
  '/api/cases/:id/risk-cockpit',
  '/api/cases/:id/risk-cockpit/tasks',
  '/api/cases/:id/risk-cockpit/tasks/:id/resolution',
  '/api/cases/:id/transition',
  '/api/cds/check',
  '/api/comments',
  '/api/comments/:id',
  '/api/comments/recent',
  '/api/communication-events',
  '/api/communication-requests',
  '/api/communication-requests/:id',
  '/api/communication-requests/:id/resolve-followup',
  '/api/communication-requests/:id/responses',
  '/api/communication-requests/export',
  '/api/communications/inbound',
  '/api/communications/inbound/:id/detail',
  '/api/communications/inbound/:id/source-mapping',
  '/api/communications/inbound/mcs',
  '/api/communications/inbound/phone',
  '/api/communications/inbound/signals',
  '/api/communications/inbound/signals/:id',
  '/api/communications/inbound/signals/tasks',
  '/api/community-activities',
  '/api/community-activities/:id',
  '/api/conference-notes',
  '/api/conference-notes/:id',
  '/api/conference-notes/:id/generate-report',
  '/api/conference-notes/:id/pdf',
  '/api/conference-notes/:id/tasks',
  '/api/conference-notes/participant-suggestions',
  '/api/consent-records',
  '/api/consent-records/:id',
  '/api/consent-records/:id/revoke',
  '/api/contact-profiles',
  '/api/cycle-holds',
  '/api/dashboard/dispensing-stats',
  '/api/dashboard/medication-deadlines',
  '/api/dashboard/monthly-stats',
  '/api/dashboard/overdue',
  '/api/dashboard/cockpit',
  '/api/dashboard/cockpit/comments',
  '/api/dashboard/cockpit/details',
  '/api/dashboard/cockpit/inbound',
  '/api/dashboard/cockpit/report-billing',
  '/api/dashboard/cockpit/stock-risks',
  '/api/dashboard/cockpit/summary',
  '/api/dashboard/cockpit/team',
  '/api/dashboard/clerk-support',
  '/api/dashboard/workflow',
  '/api/dispense-audits',
  '/api/dispense-queue',
  '/api/dispense-results',
  '/api/dispense-results/:id',
  '/api/dispense-tasks',
  '/api/dispense-tasks/:id',
  '/api/dispense-tasks/:id/groups',
  '/api/dispense-tasks/:id/lines',
  '/api/dispense-tasks/:id/verify-barcode',
  '/api/dispense-tasks/:id/workbench',
  '/api/dispense-workbench/patients',
  '/api/document-delivery-rules',
  '/api/document-delivery-rules/:id',
  '/api/drug-alert-rules',
  '/api/drug-alert-rules/:id',
  '/api/drug-master-import-logs',
  '/api/drug-master-imports/hot',
  '/api/drug-master-imports/manual-clinical',
  '/api/drug-master-imports/mhlw-generic',
  '/api/drug-master-imports/mhlw-price',
  '/api/drug-master-imports/pmda',
  '/api/drug-master-imports/ssk',
  '/api/drug-master-imports/status',
  '/api/drug-masters',
  '/api/drug-masters/:id',
  '/api/drug-masters/:id/generic-recommendations',
  '/api/drug-masters/:id/ingredient-group',
  '/api/drug-masters/:id/package-insert',
  '/api/drug-masters/batch',
  '/api/external-access',
  '/api/external-access/:token',
  '/api/external-access/:token/self-report',
  '/api/external-professionals',
  '/api/external-professionals/:id',
  '/api/external-professionals/:id/communications',
  '/api/external-professionals/:id/patients',
  '/api/external-professionals/suggestions',
  '/api/facilities',
  '/api/facilities/:id',
  '/api/facilities/:id/contacts',
  '/api/facilities/:id/patients',
  '/api/facility-visit-batches',
  '/api/facility-visit-batches/:id',
  '/api/facility-visit-batches/visit-days',
  '/api/files/:id/download',
  '/api/files/:id/presigned-download',
  '/api/files/complete',
  '/api/files/presigned-upload',
  '/api/first-visit-documents',
  '/api/first-visit-documents/:id',
  '/api/first-visit-documents/print-batch',
  '/api/handoff-board',
  '/api/handoff-board/items',
  '/api/handoff-board/items/:id/read',
  '/api/handoff-board/items/:id/resolve',
  '/api/health',
  '/api/incident-reports',
  '/api/incident-reports/:id',
  '/api/inquiry-records',
  '/api/inquiry-records/:id',
  '/api/integration/clinical-sync/conflicts',
  '/api/integration/clinical-sync/conflicts/:id',
  '/api/integration/clinical-sync/conflicts/:id/requeue',
  '/api/interventions',
  '/api/interventions/:id',
  '/api/jobs',
  '/api/jobs/:jobType',
  '/api/jobs/flush-metrics',
  '/api/management-plans',
  '/api/management-plans/:id',
  '/api/management-plans/:id/pdf',
  '/api/me/activity-summary',
  '/api/me/logout-all',
  '/api/me/mfa/disable',
  '/api/me/mfa/setup',
  '/api/me/mfa/verify',
  '/api/me/org',
  '/api/me/password',
  '/api/me/preferences',
  '/api/me/profile',
  '/api/me/site',
  '/api/me/sites',
  '/api/medication-cycles',
  '/api/medication-cycles/:id/history',
  '/api/medication-cycles/:id/transition',
  '/api/medication-issues',
  '/api/medication-issues/:id',
  '/api/medication-profiles',
  '/api/medication-sets/workspace',
  '/api/meta/route-catalog',
  '/api/nav-badges',
  '/api/notification-rules',
  '/api/notification-rules/:id',
  '/api/notifications',
  '/api/notifications/stream',
  '/api/onboarding/renewal-board',
  '/api/packaging-methods',
  '/api/packaging-methods/:id',
  '/api/partner-visit-records',
  '/api/partner-visit-records/:id/physician-report-draft',
  '/api/partner-visit-records/:id/review',
  '/api/partner-visit-records/:id/submit',
  '/api/partner-pharmacies',
  '/api/patient-self-reports',
  '/api/patient-self-reports/:id',
  '/api/patient-self-reports/:id/convert-to-task',
  '/api/patient-share-cases',
  '/api/patient-share-cases/:id',
  '/api/patient-share-cases/:id/activate',
  '/api/patient-share-cases/:id/consents',
  '/api/patient-share-cases/:id/consents/:id/revoke',
  '/api/patient-share-cases/:id/correction-requests',
  '/api/patient-share-cases/:id/patient-link',
  '/api/patients',
  '/api/patients/:id',
  '/api/patients/:id/archive',
  '/api/patients/:id/billing-profile',
  '/api/patients/:id/care-team',
  '/api/patients/:id/communications',
  '/api/patients/:id/conditions',
  '/api/patients/:id/contacts',
  '/api/patients/:id/documents',
  '/api/patients/:id/external-clinical-references/verify',
  '/api/patients/:id/field-revisions',
  '/api/patients/:id/header-summary',
  '/api/patients/:id/home-operations',
  '/api/patients/:id/insurance',
  '/api/patients/:id/insurance/:id',
  '/api/patients/:id/labs',
  '/api/patients/:id/labs/:id',
  '/api/patients/:id/mcs',
  '/api/patients/:id/mcs/logs',
  '/api/patients/:id/mcs-sync',
  '/api/patients/:id/medication-calendar/pdf',
  '/api/patients/:id/medication-stock',
  '/api/patients/:id/medication-timeline',
  '/api/patients/:id/medications/pdf',
  '/api/patients/:id/movement-timeline',
  '/api/patients/:id/overview',
  '/api/patients/:id/packaging',
  '/api/patients/:id/prescriptions',
  '/api/patients/:id/prescriptions/e-prescription',
  '/api/patients/:id/prescriptions/export',
  '/api/patients/:id/qualification-check',
  '/api/patients/:id/readiness',
  '/api/patients/:id/restore',
  '/api/patients/:id/structured-care',
  '/api/patients/:id/timeline/:id',
  '/api/patients/:id/visit-brief',
  '/api/patients/:id/visit-constraints',
  '/api/patients/:id/visit-records/pdf',
  '/api/patients/:id/visits',
  '/api/patients/:id/workflow-preview',
  '/api/patients/board',
  '/api/patients/check-duplicate',
  '/api/patients/export',
  '/api/patients/medications/bulk-export',
  '/api/org/members',
  '/api/pca-pump-rentals',
  '/api/pca-pump-rentals/:id',
  '/api/pca-pumps',
  '/api/pca-pumps/:id',
  '/api/pharmacist-shift-templates',
  '/api/pharmacist-shift-templates/:id',
  '/api/pharmacist-shift-templates/apply',
  '/api/pharmacist-shifts',
  '/api/pharmacist-shifts/available',
  '/api/pharmacist-shifts/bulk',
  '/api/pharmacists',
  '/api/pharmacists/:id',
  '/api/pharmacists/import',
  '/api/pharmacy-drug-stock-requests',
  '/api/pharmacy-drug-stock-requests/:id',
  '/api/pharmacy-drug-stock-templates',
  '/api/pharmacy-drug-stock-templates/:id',
  '/api/pharmacy-drug-stock-templates/:id/apply',
  '/api/pharmacy-drug-stocks',
  '/api/pharmacy-drug-stocks/bulk',
  '/api/pharmacy-drug-stocks/copy',
  '/api/pharmacy-drug-stocks/export',
  '/api/pharmacy-drug-stocks/history',
  '/api/pharmacy-drug-stocks/impact',
  '/api/pharmacy-drug-stocks/review',
  '/api/pharmacy-drug-stocks/safety-follow-up',
  '/api/pharmacy-drug-stocks/template',
  '/api/pharmacy-drug-stocks/usage-mismatch',
  '/api/pharmacy-cooperation-message-threads',
  '/api/pharmacy-contracts',
  '/api/pharmacy-contracts/:id/documents',
  '/api/pharmacy-contracts/:id/versions',
  '/api/pharmacy-partnerships',
  '/api/pharmacy-partnerships/:id/activate',
  '/api/pharmacy-visit-requests',
  '/api/pharmacy-visit-requests/:id/decision',
  '/api/pharmacy-sites',
  '/api/pharmacy-sites/:id',
  '/api/pharmacy-sites/:id/insurance-configs',
  '/api/pharmacy-sites/:id/insurance-configs/:id',
  '/api/phos/:path*',
  '/api/prescriber-institutions',
  '/api/prescriber-institutions/:id',
  '/api/prescriber-institutions/suggestion',
  '/api/prescription-intakes',
  '/api/prescription-intakes/:id',
  '/api/prescription-intakes/:id/medication-stock/retry',
  '/api/prescription-intakes/facility-batch',
  '/api/prescription-intakes/triage',
  '/api/prescription-lines/:id',
  '/api/presence',
  '/api/push-subscription',
  '/api/qr-scan-drafts',
  '/api/qr-scan-drafts/:id',
  '/api/qr-scan-drafts/:id/confirm',
  '/api/referrals',
  '/api/residual-medications',
  '/api/saved-views',
  '/api/saved-views/:id',
  '/api/service-areas',
  '/api/service-areas/:id',
  '/api/set-audits',
  '/api/set-batches',
  '/api/set-batches/:id',
  '/api/set-plans',
  '/api/set-plans/:id',
  '/api/set-plans/:id/batches/bulk-set',
  '/api/set-plans/:id/batches/cell',
  '/api/set-plans/:id/calendar',
  '/api/set-plans/:id/generate-batches',
  '/api/settings',
  '/api/settings/operational-policy',
  '/api/staff-workload',
  '/api/tasks',
  '/api/tasks/:id',
  '/api/tasks/:id/prescription-supply/resolve',
  '/api/tasks/bulk',
  '/api/tasks/health-board',
  '/api/templates',
  '/api/templates/:id',
  '/api/tracing-reports',
  '/api/tracing-reports/:id',
  '/api/tracing-reports/:id/pdf',
  '/api/visit-brief-feedback',
  '/api/visit-preparations/:id',
  '/api/visit-preparations/:id/brief',
  '/api/visit-preparations/brief-batch',
  '/api/visit-records',
  '/api/visit-records/:id',
  '/api/visit-records/:id/handoff',
  '/api/visit-records/:id/handoff/extract',
  '/api/visit-records/:id/handoff/supervision-confirm',
  '/api/visit-records/:id/handoff/supervision-request',
  '/api/visit-records/:id/medication-stock-observations',
  '/api/visit-records/:id/pdf',
  '/api/visit-records/:id/reflected-fields',
  '/api/visit-routes',
  '/api/visit-routes/reorder',
  '/api/visit-vehicle-resources',
  '/api/visit-vehicle-resources/:id',
  '/api/visit-schedule-proposals',
  '/api/visit-schedule-proposals/:id',
  '/api/visit-schedule-proposals/billing-preview',
  '/api/visit-schedule-proposals/billing-preview-batch',
  '/api/visit-schedule-proposals/overload-rebalance-preview',
  '/api/visit-schedule-proposals/reorder',
  '/api/visit-schedules',
  '/api/visit-schedules/:id',
  '/api/visit-schedules/:id/conflict-reconfirmation',
  '/api/visit-schedules/:id/reopen',
  '/api/visit-schedules/:id/reschedule',
  '/api/visit-schedules/:id/reschedule/approve',
  '/api/visit-schedules/generate',
  '/api/visit-schedules/reorder',
  '/api/visit-schedules/day-board',
  '/api/visits/today-preparation',
  '/api/webhooks/twilio/message-status',
  '/api/webhooks/yrese',
  '/api/workflow-exceptions/:id',
] as const;

type CompiledRouteTemplate = {
  template: string;
  segments: string[];
  staticSegmentCount: number;
  catchAllIndex: number;
};

function isRouteParameterSegment(segment: string) {
  return segment.startsWith(':');
}

function isCatchAllRouteSegment(segment: string) {
  return segment.endsWith('*');
}

function getStaticRouteSegmentCount(segments: string[]) {
  return segments.filter((segment) => !isRouteParameterSegment(segment)).length;
}

const compiledApiRouteTemplates: CompiledRouteTemplate[] = API_ROUTE_TEMPLATES.map((template) => {
  const segments = template.split('/').filter(Boolean);
  return {
    template,
    segments,
    staticSegmentCount: getStaticRouteSegmentCount(segments),
    catchAllIndex: segments.findIndex(isCatchAllRouteSegment),
  };
}).sort((left, right) => {
  if (right.staticSegmentCount !== left.staticSegmentCount) {
    return right.staticSegmentCount - left.staticSegmentCount;
  }
  return right.segments.length - left.segments.length;
});

const RATE_LIMIT_CANONICAL_ROUTE_ALIASES = new Map<string, string>();

function normalizePathname(pathname: string) {
  const [pathWithoutQuery] = pathname.split('?');
  const collapsed = (pathWithoutQuery || '/').replace(/\/{2,}/g, '/');
  return collapsed.length > 1 ? collapsed.replace(/\/+$/, '') : collapsed;
}

function routeTemplateMatches(template: CompiledRouteTemplate, pathSegments: string[]) {
  if (template.catchAllIndex === -1 && pathSegments.length !== template.segments.length) {
    return false;
  }
  if (template.catchAllIndex !== -1 && pathSegments.length <= template.catchAllIndex) {
    return false;
  }

  return template.segments.every((segment, index) => {
    if (isCatchAllRouteSegment(segment)) return true;
    if (isRouteParameterSegment(segment)) return Boolean(pathSegments[index]);
    return segment === pathSegments[index];
  });
}

export function canonicalizeRateLimitPath(pathname: string) {
  const normalized = normalizePathname(pathname);
  if (normalized !== '/api' && !normalized.startsWith('/api/')) {
    return normalized;
  }

  const pathSegments = normalized.split('/').filter(Boolean);
  const matched = compiledApiRouteTemplates.find((template) =>
    routeTemplateMatches(template, pathSegments),
  );
  if (!matched) return UNKNOWN_API_RATE_LIMIT_PATH;
  return RATE_LIMIT_CANONICAL_ROUTE_ALIASES.get(matched.template) ?? matched.template;
}
