import type { RouteCatalogEntry } from './route-catalog.types';

export const PATIENT_SCHEDULE_ROUTE_ENTRIES: RouteCatalogEntry[] = [
  {
    path: '/api/patients',
    methods: ['GET'],
    permission: 'canViewDashboard',
    description: '患者一覧取得',
    area: 'patients',
  },
  {
    path: '/api/patients',
    methods: ['POST'],
    permission: 'canVisit',
    description: '患者登録',
    area: 'patients',
  },
  {
    path: '/api/patients/:id',
    methods: ['GET'],
    permission: 'canViewDashboard',
    description: '患者詳細取得',
    area: 'patients',
  },
  {
    path: '/api/patients/:id',
    methods: ['PATCH'],
    permission: 'canVisit',
    description: '患者詳細更新',
    area: 'patients',
  },
  {
    path: '/api/patients/:id/overview',
    methods: ['GET'],
    permission: 'canViewDashboard',
    description: '患者詳細ワークスペース概要取得',
    area: 'patients',
  },
  {
    path: '/api/patients/:id/medication-stock',
    methods: ['GET'],
    permission: 'canViewDashboard',
    description: '患者別の外用薬・頓服薬残数台帳サマリー取得',
    area: 'patients',
  },
  {
    path: '/api/patients/:id/mcs',
    methods: ['GET'],
    permission: 'canViewDashboard',
    description: '患者MCS連携概要取得',
    area: 'patients',
  },
  {
    path: '/api/patients/:id/mcs',
    methods: ['PATCH'],
    permission: 'canVisit',
    description: '患者MCS連携プロフィール更新',
    area: 'patients',
  },
  {
    path: '/api/patients/board',
    methods: ['GET'],
    permission: 'canViewDashboard',
    description: '患者ボード一覧・対応状況集計取得',
    area: 'patients',
  },
  {
    path: '/api/patients/check-duplicate',
    methods: ['GET'],
    permission: 'canViewDashboard',
    description: '患者登録前の重複候補検索',
    area: 'patients',
  },
  {
    path: '/api/patients/:id/prescriptions',
    methods: ['GET'],
    permission: 'canViewDashboard',
    description: '患者別処方履歴と処方差分レビュー取得',
    area: 'prescriptions',
  },
  {
    path: '/api/patients/:id/prescriptions/export',
    methods: ['GET'],
    permission: 'canVisit',
    description: '患者別処方履歴 CSV エクスポート',
    area: 'prescriptions',
  },
  {
    path: '/api/first-visit-documents',
    methods: ['GET', 'POST'],
    permission: 'canVisit',
    description: '初回訪問文書・緊急連絡先・交付記録の一覧取得と作成',
    area: 'patients',
  },
  {
    path: '/api/patient-share-cases',
    methods: ['GET'],
    permission: 'canManagePatientSharing',
    description: '薬局間連携の患者共有ケース一覧取得',
    area: 'patients',
  },
  {
    path: '/api/patient-share-cases',
    methods: ['POST'],
    permission: 'canManagePatientSharing',
    description: '薬局間連携の患者共有ケース作成',
    area: 'patients',
  },
  {
    path: '/api/patient-share-cases/:id',
    methods: ['PATCH'],
    permission: 'canManagePatientSharing',
    description: '患者共有ケースの共有範囲更新',
    area: 'patients',
  },
  {
    path: '/api/patient-share-cases/:id/activate',
    methods: ['POST'],
    permission: 'canManagePatientSharing',
    description: '同意・患者紐づけ・双方承認を確認した患者共有ケースの有効化',
    area: 'patients',
  },
  {
    path: '/api/patient-share-cases/:id/consents',
    methods: ['GET'],
    permission: 'canVisit',
    description: '患者共有ケースの同意メタ情報一覧取得',
    area: 'patients',
  },
  {
    path: '/api/patient-share-cases/:id/consents',
    methods: ['POST'],
    permission: 'canManagePatientSharing',
    description: '患者共有ケースの同意登録・添付紐づけ',
    area: 'patients',
  },
  {
    path: '/api/patient-share-cases/:id/consents/:id/revoke',
    methods: ['POST'],
    permission: 'canManagePatientSharing',
    description: '患者共有同意の撤回と共有停止',
    area: 'patients',
  },
  {
    path: '/api/patient-share-cases/:id/patient-link',
    methods: ['PATCH'],
    permission: 'canManagePatientSharing',
    description: '患者共有ケースの患者リンク承認・受諾・辞退',
    area: 'patients',
  },
  {
    path: '/api/patient-share-cases/:id/correction-requests',
    methods: ['GET'],
    permission: 'canVisit',
    description: '患者共有ケースの修正・追記依頼一覧取得',
    area: 'patients',
  },
  {
    path: '/api/patient-share-cases/:id/correction-requests',
    methods: ['POST'],
    permission: 'canManagePatientSharing',
    description: '相手薬局所有データへの修正・追記依頼作成',
    area: 'patients',
  },
  {
    path: '/api/cases',
    methods: ['GET', 'POST'],
    permission: 'canVisit',
    description: 'ケース一覧取得と新規作成',
    area: 'cases',
  },
  {
    path: '/api/cases/:id/transition',
    methods: ['PATCH'],
    permission: 'canVisit',
    description: 'ケース状態遷移',
    area: 'cases',
  },
  {
    path: '/api/referrals',
    methods: ['POST'],
    permission: 'canVisit',
    description: '紹介受付から患者と初回ケースを原子的に登録',
    area: 'cases',
  },
  {
    path: '/api/visit-schedules',
    methods: ['GET', 'POST'],
    permission: 'canVisit',
    description: '訪問予定一覧取得と作成',
    area: 'schedules',
  },
  {
    path: '/api/visit-schedules/:id',
    methods: ['GET'],
    permission: 'canViewDashboard',
    description: '訪問予定詳細取得',
    area: 'schedules',
  },
  {
    path: '/api/visit-schedules/:id',
    methods: ['PATCH', 'DELETE'],
    permission: 'canVisit',
    description: '訪問予定更新・取消',
    area: 'schedules',
  },
  {
    path: '/api/visit-schedules/generate',
    methods: ['POST'],
    permission: 'canVisit',
    description: '廃止済み: 訪問予定の直接一括生成は使わず訪問候補生成を使用',
    area: 'schedules',
  },
  {
    path: '/api/visit-schedules/day-board',
    methods: ['GET'],
    permission: 'canVisit',
    description: '日次訪問予定ボード取得',
    area: 'schedules',
  },
  {
    path: '/api/visit-schedule-proposals',
    methods: ['GET', 'POST', 'PUT'],
    permission: 'canVisit',
    description: '訪問候補一覧取得・候補生成・連絡状態更新',
    area: 'schedules',
  },
  {
    path: '/api/visit-schedule-proposals/overload-rebalance-preview',
    methods: ['POST'],
    permission: 'canVisit',
    description: '訪問候補の過密前倒しプレビュー',
    area: 'schedules',
  },
];
