import type { PermissionKey } from '@/lib/auth/permissions';

export type RouteCatalogEntry = {
  path: string;
  methods: string[];
  permission: PermissionKey | 'authenticated' | 'purpose-based' | 'canAdmin|apiKey' | 'public';
  description: string;
  area:
    | 'patients'
    | 'cases'
    | 'schedules'
    | 'visits'
    | 'prescriptions'
    | 'dispensing'
    | 'reports'
    | 'shifts'
    | 'dashboard'
    | 'billing'
    | 'auditing'
    | 'masters'
    | 'files'
    | 'system';
};

export const routeCatalogMetadata = {
  scope: 'curated_operational_routes',
  exhaustive: false,
} as const;

export const routeCatalog: RouteCatalogEntry[] = [
  {
    path: '/api/patients',
    methods: ['GET', 'POST'],
    permission: 'canVisit',
    description: '患者一覧取得と患者登録',
    area: 'patients',
  },
  {
    path: '/api/patients/:id',
    methods: ['GET', 'PATCH'],
    permission: 'canVisit',
    description: '患者詳細取得と更新',
    area: 'patients',
  },
  {
    path: '/api/patients/:id/prescriptions/export',
    methods: ['GET'],
    permission: 'canVisit',
    description: '患者別処方履歴 CSV エクスポート',
    area: 'prescriptions',
  },
  {
    path: '/api/patient-share-cases',
    methods: ['GET'],
    permission: 'canVisit',
    description: '薬局間連携の患者共有ケース一覧取得',
    area: 'patients',
  },
  {
    path: '/api/patient-share-cases',
    methods: ['POST'],
    permission: 'canManagePatientSharing',
    description: '薬局間連携の患者共有ケース作成',
    area: 'patients',
  },
  {
    path: '/api/patient-share-cases/:id',
    methods: ['PATCH'],
    permission: 'canManagePatientSharing',
    description: '患者共有ケースの共有範囲更新',
    area: 'patients',
  },
  {
    path: '/api/patient-share-cases/:id/activate',
    methods: ['POST'],
    permission: 'canManagePatientSharing',
    description: '同意・患者紐づけ・双方承認を確認した患者共有ケースの有効化',
    area: 'patients',
  },
  {
    path: '/api/patient-share-cases/:id/consents',
    methods: ['GET'],
    permission: 'canVisit',
    description: '患者共有ケースの同意メタ情報一覧取得',
    area: 'patients',
  },
  {
    path: '/api/patient-share-cases/:id/consents',
    methods: ['POST'],
    permission: 'canManagePatientSharing',
    description: '患者共有ケースの同意登録・添付紐づけ',
    area: 'patients',
  },
  {
    path: '/api/patient-share-cases/:id/consents/:id/revoke',
    methods: ['POST'],
    permission: 'canManagePatientSharing',
    description: '患者共有同意の撤回と共有停止',
    area: 'patients',
  },
  {
    path: '/api/patient-share-cases/:id/patient-link',
    methods: ['PATCH'],
    permission: 'canManagePatientSharing',
    description: '患者共有ケースの患者リンク承認・受諾・辞退',
    area: 'patients',
  },
  {
    path: '/api/patient-share-cases/:id/correction-requests',
    methods: ['GET'],
    permission: 'canVisit',
    description: '患者共有ケースの修正・追記依頼一覧取得',
    area: 'patients',
  },
  {
    path: '/api/patient-share-cases/:id/correction-requests',
    methods: ['POST'],
    permission: 'canManagePatientSharing',
    description: '相手薬局所有データへの修正・追記依頼作成',
    area: 'patients',
  },
  {
    path: '/api/cases',
    methods: ['GET', 'POST'],
    permission: 'canVisit',
    description: 'ケース一覧取得と新規作成',
    area: 'cases',
  },
  {
    path: '/api/cases/:id/transition',
    methods: ['PATCH'],
    permission: 'canVisit',
    description: 'ケース状態遷移',
    area: 'cases',
  },
  {
    path: '/api/referrals',
    methods: ['POST'],
    permission: 'canVisit',
    description: '紹介受付から患者と初回ケースを原子的に登録',
    area: 'cases',
  },
  {
    path: '/api/visit-schedules',
    methods: ['GET', 'POST'],
    permission: 'canVisit',
    description: '訪問予定一覧取得と作成',
    area: 'schedules',
  },
  {
    path: '/api/visit-schedules/generate',
    methods: ['POST'],
    permission: 'canVisit',
    description: '定期訪問の一括生成',
    area: 'schedules',
  },
  {
    path: '/api/visit-records',
    methods: ['GET', 'POST'],
    permission: 'canVisit',
    description: '訪問記録一覧取得と保存',
    area: 'visits',
  },
  {
    path: '/api/visit-records/:id',
    methods: ['GET', 'PATCH'],
    permission: 'canVisit',
    description: '訪問記録詳細取得と更新',
    area: 'visits',
  },
  {
    path: '/api/visit-records/:id/pdf',
    methods: ['GET'],
    permission: 'canVisit',
    description: '訪問記録 PDF 出力',
    area: 'visits',
  },
  {
    path: '/api/pharmacy-visit-requests',
    methods: ['GET'],
    permission: 'canManagePatientSharing',
    description: '薬局間協力訪問依頼一覧取得',
    area: 'visits',
  },
  {
    path: '/api/pharmacy-visit-requests',
    methods: ['POST'],
    permission: 'canManagePatientSharing',
    description: '患者共有ケースに紐づく協力訪問依頼作成',
    area: 'visits',
  },
  {
    path: '/api/pharmacy-visit-requests/:id/decision',
    methods: ['POST'],
    permission: 'canManagePatientSharing',
    description: '協力薬局による訪問依頼の受諾・辞退',
    area: 'visits',
  },
  {
    path: '/api/partner-visit-records',
    methods: ['GET'],
    permission: 'canManagePatientSharing',
    description: '協力薬局訪問記録一覧取得',
    area: 'visits',
  },
  {
    path: '/api/partner-visit-records',
    methods: ['POST'],
    permission: 'canManagePatientSharing',
    description: '協力薬局訪問記録の下書き保存',
    area: 'visits',
  },
  {
    path: '/api/partner-visit-records/:id/submit',
    methods: ['POST'],
    permission: 'canManagePatientSharing',
    description: '協力薬局訪問記録の提出とレセ補助生成',
    area: 'visits',
  },
  {
    path: '/api/partner-visit-records/:id/review',
    methods: ['POST'],
    permission: 'canManagePatientSharing',
    description: '基幹薬局による協力薬局訪問記録の確認・差戻し',
    area: 'visits',
  },
  {
    path: '/api/partner-visit-records/:id/physician-report-draft',
    methods: ['POST'],
    permission: 'canAuthorReport',
    description: '確認済み協力薬局訪問記録から医師向け報告書ドラフトを作成',
    area: 'reports',
  },
  {
    path: '/api/prescription-intakes',
    methods: ['GET', 'POST'],
    permission: 'canDispense',
    description: '処方箋受付一覧取得と登録',
    area: 'prescriptions',
  },
  {
    path: '/api/medication-cycles/:id/transition',
    methods: ['PATCH'],
    permission: 'canDispense',
    description: 'MedicationCycle の状態遷移',
    area: 'prescriptions',
  },
  {
    path: '/api/dispense-queue',
    methods: ['GET'],
    permission: 'canDispense',
    description: '調剤キュー一覧取得',
    area: 'dispensing',
  },
  {
    path: '/api/dispense-results',
    methods: ['POST'],
    permission: 'canDispense',
    description: '調剤実績登録',
    area: 'dispensing',
  },
  {
    path: '/api/dispense-audits',
    methods: ['GET', 'POST'],
    permission: 'canAuditDispense',
    description: '鑑査一覧取得と鑑査実行',
    area: 'dispensing',
  },
  {
    path: '/api/care-reports',
    methods: ['GET', 'POST'],
    permission: 'canReport',
    description: '報告書一覧取得と作成',
    area: 'reports',
  },
  {
    path: '/api/care-reports/:id',
    methods: ['GET', 'PATCH'],
    permission: 'purpose-based',
    description: '報告書詳細取得と編集（閲覧は canReport、編集は canAuthorReport）',
    area: 'reports',
  },
  {
    path: '/api/care-reports/generate-from-visit',
    methods: ['POST'],
    permission: 'canAuthorReport',
    description: '訪問記録から報告書を生成',
    area: 'reports',
  },
  {
    path: '/api/care-reports/today-workspace',
    methods: ['GET'],
    permission: 'canReport',
    description: '当日報告ワークスペース取得',
    area: 'reports',
  },
  {
    path: '/api/care-reports/:id/send',
    methods: ['POST'],
    permission: 'canSendCareReport',
    description: '報告書送付',
    area: 'reports',
  },
  {
    path: '/api/care-reports/:id/pdf',
    methods: ['GET'],
    permission: 'canSendCareReport',
    description: '報告書 PDF 出力',
    area: 'reports',
  },
  {
    path: '/api/care-reports/:id/print-audit',
    methods: ['POST'],
    permission: 'canSendCareReport',
    description: '報告書印刷監査と印刷用データ取得',
    area: 'reports',
  },
  {
    path: '/api/care-reports/analytics',
    methods: ['GET'],
    permission: 'canSendCareReport',
    description: '報告書送達分析',
    area: 'reports',
  },
  {
    path: '/api/care-reports/reminders',
    methods: ['POST'],
    permission: 'canSendCareReport',
    description: '報告書返信リマインド作成',
    area: 'reports',
  },
  {
    path: '/api/external-access',
    methods: ['GET', 'POST'],
    permission: 'canReport',
    description: '患者向け外部共有リンクの一覧取得と発行',
    area: 'reports',
  },
  {
    path: '/api/external-access/:token',
    methods: ['GET'],
    permission: 'public',
    description: 'OTP付き外部共有リンクの公開閲覧',
    area: 'reports',
  },
  {
    path: '/api/external-access/:token/self-report',
    methods: ['POST'],
    permission: 'public',
    description: '外部共有リンクからの患者自己申告登録',
    area: 'reports',
  },
  {
    path: '/api/communication-requests',
    methods: ['GET', 'POST'],
    permission: 'canReport',
    description: '連携依頼一覧取得と作成',
    area: 'reports',
  },
  {
    path: '/api/communication-requests/:id',
    methods: ['GET', 'PATCH'],
    permission: 'canReport',
    description: '連携依頼詳細取得と更新',
    area: 'reports',
  },
  {
    path: '/api/communication-requests/export',
    methods: ['GET'],
    permission: 'canReport',
    description: '連携依頼 CSV エクスポート（internal は追加条件と強い権限を要求）',
    area: 'reports',
  },
  {
    path: '/api/communication-requests/:id/responses',
    methods: ['GET', 'POST'],
    permission: 'canReport',
    description: '連携依頼の返信一覧取得と返信記録',
    area: 'reports',
  },
  {
    path: '/api/communication-requests/:id/resolve-followup',
    methods: ['POST'],
    permission: 'canReport',
    description: '連携依頼返信のフォローアップ完了処理',
    area: 'reports',
  },
  {
    path: '/api/tracing-reports',
    methods: ['GET', 'POST'],
    permission: 'canReport',
    description: 'トレーシングレポート一覧取得と作成',
    area: 'reports',
  },
  {
    path: '/api/tracing-reports/:id/pdf',
    methods: ['GET'],
    permission: 'canReport',
    description: 'トレーシングレポート PDF 出力',
    area: 'reports',
  },
  {
    path: '/api/billing-candidates/export',
    methods: ['GET'],
    permission: 'canManageBilling',
    description: '請求候補 CSV / CLAIMS-XML エクスポート',
    area: 'billing',
  },
  {
    path: '/api/visit-billing-candidates',
    methods: ['GET', 'POST'],
    permission: 'canManageBilling',
    description: '薬局間協力訪問の請求候補一覧取得と月次生成',
    area: 'billing',
  },
  {
    path: '/api/visit-billing-candidates/summary',
    methods: ['GET'],
    permission: 'canManageBilling',
    description: '薬局間協力訪問の月次実績集計',
    area: 'billing',
  },
  {
    path: '/api/pharmacy-invoices',
    methods: ['GET', 'POST'],
    permission: 'canManageBilling',
    description: '薬局間請求書・無償実績報告書の一覧取得とドラフト生成',
    area: 'billing',
  },
  {
    path: '/api/pharmacy-invoices/:id',
    methods: ['PATCH'],
    permission: 'canManageBilling',
    description: '薬局間請求書・無償実績報告書の発行・送付・入金・取消状態更新',
    area: 'billing',
  },
  {
    path: '/api/pharmacy-invoices/:id/pdf',
    methods: ['GET'],
    permission: 'canManageBilling',
    description: '薬局間請求書・無償実績報告書 PDF 出力',
    area: 'billing',
  },
  {
    path: '/api/audit-logs/export',
    methods: ['GET'],
    permission: 'canAdmin',
    description: '監査ログ CSV / JSON エクスポート',
    area: 'auditing',
  },
  {
    path: '/api/pharmacist-shifts',
    methods: ['GET', 'POST'],
    permission: 'canAdmin',
    description: 'シフト一覧取得と登録',
    area: 'shifts',
  },
  {
    path: '/api/pharmacist-shifts/available',
    methods: ['GET'],
    permission: 'canVisit',
    description: '空き薬剤師検索',
    area: 'shifts',
  },
  {
    path: '/api/dashboard/overdue',
    methods: ['GET'],
    permission: 'canViewDashboard',
    description: '期限超過の訪問・報告・タスク一覧',
    area: 'dashboard',
  },
  {
    path: '/api/dashboard/monthly-stats',
    methods: ['GET'],
    permission: 'canViewDashboard',
    description: '患者別×保険種別の月間訪問回数進捗',
    area: 'dashboard',
  },
  {
    path: '/api/dashboard/workflow',
    methods: ['GET'],
    permission: 'canViewDashboard',
    description: '工程別ワークフロー集計',
    area: 'dashboard',
  },
  {
    path: '/api/drug-masters',
    methods: ['GET'],
    permission: 'canAdmin',
    description: '医薬品マスタ検索',
    area: 'masters',
  },
  {
    path: '/api/drug-master-imports/ssk',
    methods: ['POST'],
    permission: 'canAdmin',
    description: 'SSK 医薬品マスタ取込',
    area: 'masters',
  },
  {
    path: '/api/drug-master-imports/mhlw-price',
    methods: ['POST'],
    permission: 'canAdmin',
    description: 'MHLW 薬価基準収載品目取込',
    area: 'masters',
  },
  {
    path: '/api/drug-master-imports/mhlw-generic',
    methods: ['POST'],
    permission: 'canAdmin',
    description: 'MHLW 一般名処方/後発フラグ取込',
    area: 'masters',
  },
  {
    path: '/api/drug-master-imports/hot',
    methods: ['POST'],
    permission: 'canAdmin',
    description: 'HOT コードマスタ取込',
    area: 'masters',
  },
  {
    path: '/api/drug-master-imports/pmda',
    methods: ['POST'],
    permission: 'canAdmin',
    description: 'PMDA 添付文書 XML 取込',
    area: 'masters',
  },
  {
    path: '/api/drug-master-imports/manual-clinical',
    methods: ['POST'],
    permission: 'canAdmin',
    description: '手動投入用の高齢者/腎機能/ハイリスク薬ルール取込',
    area: 'masters',
  },
  {
    path: '/api/drug-master-imports/status',
    methods: ['GET'],
    permission: 'canAdmin',
    description: '医薬品マスタ取込ソース別の鮮度・失敗状態',
    area: 'masters',
  },
  {
    path: '/api/drug-master-import-logs',
    methods: ['GET'],
    permission: 'canAdmin',
    description: '医薬品マスタ取込履歴と失敗ログ',
    area: 'masters',
  },
  {
    path: '/api/pharmacy-drug-stocks/export',
    methods: ['GET'],
    permission: 'canAdmin',
    description: '採用薬 CSV エクスポート',
    area: 'masters',
  },
  {
    path: '/api/pharmacy-drug-stocks/template',
    methods: ['GET'],
    permission: 'canAdmin',
    description: '採用薬 CSV 取込テンプレート',
    area: 'masters',
  },
  {
    path: '/api/partner-pharmacies',
    methods: ['GET'],
    permission: 'canVisit',
    description: '協力薬局マスタ一覧取得',
    area: 'masters',
  },
  {
    path: '/api/partner-pharmacies',
    methods: ['POST'],
    permission: 'canManagePatientSharing',
    description: '協力薬局マスタ作成',
    area: 'masters',
  },
  {
    path: '/api/pharmacy-partnerships',
    methods: ['GET'],
    permission: 'canVisit',
    description: '基準薬局と協力薬局の連携一覧取得',
    area: 'masters',
  },
  {
    path: '/api/pharmacy-partnerships',
    methods: ['POST'],
    permission: 'canManagePatientSharing',
    description: '基準薬局と協力薬局の連携作成',
    area: 'masters',
  },
  {
    path: '/api/pharmacy-partnerships/:id/activate',
    methods: ['POST'],
    permission: 'canManagePatientSharing',
    description: '基準薬局と協力薬局の連携有効化',
    area: 'masters',
  },
  {
    path: '/api/pharmacy-contracts',
    methods: ['GET'],
    permission: 'canVisit',
    description: '薬局間契約マスタ一覧取得',
    area: 'masters',
  },
  {
    path: '/api/pharmacy-contracts',
    methods: ['POST'],
    permission: 'canManagePatientSharing',
    description: '薬局間契約マスタ作成',
    area: 'masters',
  },
  {
    path: '/api/pharmacy-contracts/:id/versions',
    methods: ['POST'],
    permission: 'canManagePatientSharing',
    description: '薬局間契約の新規契約版と費用条件作成',
    area: 'masters',
  },
  {
    path: '/api/pharmacy-cooperation-message-threads',
    methods: ['GET', 'POST'],
    permission: 'canManagePatientSharing',
    description: '患者共有ケース・訪問依頼別の薬局間連携メッセージ',
    area: 'patients',
  },
  {
    path: '/api/pharmacy-contracts/:id/documents',
    methods: ['GET'],
    permission: 'canVisit',
    description: '薬局間契約書の生成済み文書一覧取得',
    area: 'masters',
  },
  {
    path: '/api/pharmacy-contracts/:id/documents',
    methods: ['POST'],
    permission: 'canManagePatientSharing',
    description: '薬局間契約書テンプレートのプレビューと文書保存',
    area: 'masters',
  },
  {
    path: '/api/files/presigned-upload',
    methods: ['POST'],
    permission: 'authenticated',
    description: 'S3 presigned PUT URL 発行',
    area: 'files',
  },
  {
    path: '/api/files/complete',
    methods: ['POST'],
    permission: 'authenticated',
    description: 'アップロード完了コールバック',
    area: 'files',
  },
  {
    path: '/api/files/:id/presigned-download',
    methods: ['GET'],
    permission: 'purpose-based',
    description: '用途別権限を確認した上で S3 presigned GET URL を発行',
    area: 'files',
  },
  {
    path: '/api/files/:id/download',
    methods: ['GET'],
    permission: 'purpose-based',
    description: '用途別権限を確認した上で S3 署名付きURLへリダイレクトしてファイルをダウンロード',
    area: 'files',
  },
  {
    path: '/api/management-plans/:id/pdf',
    methods: ['GET'],
    permission: 'canVisit',
    description: '管理計画書 PDF 出力',
    area: 'patients',
  },
  {
    path: '/api/patients/:id/medications/pdf',
    methods: ['GET'],
    permission: 'canVisit',
    description: '薬歴・服薬一覧 PDF 出力',
    area: 'patients',
  },
  {
    path: '/api/patients/medications/bulk-export',
    methods: ['POST'],
    permission: 'canVisit',
    description: '患者選択済みの薬歴 PDF を ZIP 一括出力キューへ登録',
    area: 'patients',
  },
  {
    path: '/api/patients/:id/medication-calendar/pdf',
    methods: ['GET'],
    permission: 'canVisit',
    description: '服薬カレンダー PDF 出力',
    area: 'patients',
  },
  {
    path: '/api/patients/:id/visit-records/pdf',
    methods: ['GET'],
    permission: 'canVisit',
    description: '患者単位・期間指定の訪問記録一覧 PDF 出力',
    area: 'patients',
  },
  {
    path: '/api/jobs',
    methods: ['GET'],
    permission: 'canAdmin',
    description: 'ジョブ定義と最新実行状況の一覧取得',
    area: 'system',
  },
  {
    path: '/api/jobs/:jobType',
    methods: ['POST'],
    permission: 'canAdmin|apiKey',
    description: 'ジョブの手動実行またはスケジューラ実行',
    area: 'system',
  },
  {
    path: '/api/meta/route-catalog',
    methods: ['GET'],
    permission: 'canAdmin',
    description: '主要 Route Handler の運用カタログ（全 Route Handler 一覧ではない）',
    area: 'system',
  },
];
