import type { BillingRevision, BillingRuleSeed } from './types';

export const CARE_REVISION: BillingRevision = {
  code: '2024',
  label: '令和6年度 介護報酬改定',
  effectiveFrom: new Date('2024-06-01'),
  effectiveTo: null,
  source: 'https://www.mhlw.go.jp/stf/newpage_38790.html',
};

const CARE_SOURCE_URL = 'https://www.mhlw.go.jp/stf/newpage_38790.html';
const CARE_NOTICE_URL = 'https://www.mhlw.go.jp/content/12404000/1.pdf';

export const CARE_RULES_2024: BillingRuleSeed[] = [
  {
    ssot_key: 'care.home_management.pharmacy.single',
    rule_type: 'base',
    service_type: 'care_home_management',
    payer_basis: 'care',
    provider_scope: 'pharmacy',
    selection_mode: 'auto',
    calculation_unit: 'unit',
    display_order: 200,
    name: '居宅療養管理指導 薬局薬剤師 単一建物1人',
    code: 'CARE_HOME_PHARMACY_SINGLE',
    amount: 507,
    conditions: {
      building_tier: 'single',
      requires_care_manager_report: true,
    },
    evidence_requirements: {
      requires_care_manager_report: true,
      requires_medication_management_record: true,
    },
    source_url: CARE_NOTICE_URL,
    source_note: '厚労省 令和6年度介護報酬改定 居宅療養管理指導 薬局薬剤師 単一建物1人 507単位',
  },
  {
    ssot_key: 'care.home_management.pharmacy.multi_2_9',
    rule_type: 'base',
    service_type: 'care_home_management',
    payer_basis: 'care',
    provider_scope: 'pharmacy',
    selection_mode: 'auto',
    calculation_unit: 'unit',
    display_order: 210,
    name: '居宅療養管理指導 薬局薬剤師 単一建物2〜9人',
    code: 'CARE_HOME_PHARMACY_MULTI_2_9',
    amount: 376,
    conditions: {
      building_tier: 'multi_2_9',
      requires_care_manager_report: true,
    },
    evidence_requirements: {
      requires_care_manager_report: true,
      requires_medication_management_record: true,
    },
    source_url: CARE_NOTICE_URL,
    source_note: '厚労省 令和6年度介護報酬改定 居宅療養管理指導 薬局薬剤師 単一建物2〜9人 376単位',
  },
  {
    ssot_key: 'care.home_management.pharmacy.multi_10_plus',
    rule_type: 'base',
    service_type: 'care_home_management',
    payer_basis: 'care',
    provider_scope: 'pharmacy',
    selection_mode: 'auto',
    calculation_unit: 'unit',
    display_order: 220,
    name: '居宅療養管理指導 薬局薬剤師 単一建物10人以上',
    code: 'CARE_HOME_PHARMACY_MULTI_10_PLUS',
    amount: 344,
    conditions: {
      building_tier: 'multi_10_plus',
      requires_care_manager_report: true,
    },
    evidence_requirements: {
      requires_care_manager_report: true,
      requires_medication_management_record: true,
    },
    source_url: CARE_NOTICE_URL,
    source_note: '厚労省 令和6年度介護報酬改定 居宅療養管理指導 薬局薬剤師 単一建物10人以上 344単位',
  },
  {
    ssot_key: 'care.home_management.hospital.single',
    rule_type: 'base',
    service_type: 'care_home_management',
    payer_basis: 'care',
    provider_scope: 'hospital_clinic',
    selection_mode: 'manual',
    calculation_unit: 'unit',
    display_order: 230,
    name: '居宅療養管理指導 病院・診療所薬剤師 単一建物1人',
    code: 'CARE_HOME_HOSPITAL_SINGLE',
    amount: 558,
    conditions: {
      building_tier: 'single',
    },
    source_url: CARE_NOTICE_URL,
    source_note: '厚労省 令和6年度介護報酬改定 居宅療養管理指導 病院・診療所薬剤師 単一建物1人 558単位',
  },
  {
    ssot_key: 'care.home_management.hospital.multi_2_9',
    rule_type: 'base',
    service_type: 'care_home_management',
    payer_basis: 'care',
    provider_scope: 'hospital_clinic',
    selection_mode: 'manual',
    calculation_unit: 'unit',
    display_order: 240,
    name: '居宅療養管理指導 病院・診療所薬剤師 単一建物2〜9人',
    code: 'CARE_HOME_HOSPITAL_MULTI_2_9',
    amount: 414,
    conditions: {
      building_tier: 'multi_2_9',
    },
    source_url: CARE_NOTICE_URL,
    source_note: '厚労省 令和6年度介護報酬改定 居宅療養管理指導 病院・診療所薬剤師 単一建物2〜9人 414単位',
  },
  {
    ssot_key: 'care.home_management.hospital.multi_10_plus',
    rule_type: 'base',
    service_type: 'care_home_management',
    payer_basis: 'care',
    provider_scope: 'hospital_clinic',
    selection_mode: 'manual',
    calculation_unit: 'unit',
    display_order: 250,
    name: '居宅療養管理指導 病院・診療所薬剤師 単一建物10人以上',
    code: 'CARE_HOME_HOSPITAL_MULTI_10_PLUS',
    amount: 378,
    conditions: {
      building_tier: 'multi_10_plus',
    },
    source_url: CARE_NOTICE_URL,
    source_note: '厚労省 令和6年度介護報酬改定 居宅療養管理指導 病院・診療所薬剤師 単一建物10人以上 378単位',
  },
  {
    ssot_key: 'care.addition.special_region_15',
    rule_type: 'regional_addition',
    service_type: 'care_home_management',
    payer_basis: 'care',
    provider_scope: 'pharmacy',
    selection_mode: 'manual',
    calculation_unit: 'percent',
    display_order: 300,
    name: '特別地域加算',
    code: 'CARE_REGION_SPECIAL_15',
    amount: 15,
    conditions: {
      region_add_on: 'special_15',
    },
    source_url: CARE_SOURCE_URL,
    source_note: '厚労省 令和6年度介護報酬改定 特別地域加算 15%',
  },
  {
    ssot_key: 'care.addition.small_office_10',
    rule_type: 'regional_addition',
    service_type: 'care_home_management',
    payer_basis: 'care',
    provider_scope: 'pharmacy',
    selection_mode: 'manual',
    calculation_unit: 'percent',
    display_order: 310,
    name: '中山間地域等における小規模事業所加算',
    code: 'CARE_REGION_SMALL_OFFICE_10',
    amount: 10,
    conditions: {
      region_add_on: 'small_office_10',
    },
    source_url: CARE_SOURCE_URL,
    source_note: '厚労省 令和6年度介護報酬改定 中山間地域等における小規模事業所加算 10%',
  },
  {
    ssot_key: 'care.addition.resident_5',
    rule_type: 'regional_addition',
    service_type: 'care_home_management',
    payer_basis: 'care',
    provider_scope: 'pharmacy',
    selection_mode: 'manual',
    calculation_unit: 'percent',
    display_order: 320,
    name: '中山間地域等に居住する者へのサービス提供加算',
    code: 'CARE_REGION_RESIDENT_5',
    amount: 5,
    conditions: {
      region_add_on: 'resident_5',
    },
    source_url: CARE_SOURCE_URL,
    source_note: '厚労省 令和6年度介護報酬改定 中山間地域等に居住する者へのサービス提供加算 5%',
  },
  // ── 介護保険 加算（令和6年度） ──
  {
    ssot_key: 'care.addition.narcotic_management',
    rule_type: 'addition',
    service_type: 'care_home_management',
    payer_basis: 'care',
    provider_scope: 'pharmacy',
    selection_mode: 'auto',
    calculation_unit: 'unit',
    display_order: 330,
    name: '麻薬管理指導加算（介護）',
    code: 'CARE_ADD_NARCOTIC',
    amount: 100,
    conditions: {
      requires_narcotic_prescription: true,
    },
    evidence_requirements: {
      narcotic_management_record: true,
    },
    source_url: CARE_SOURCE_URL,
    source_note: '居宅療養管理指導 麻薬管理指導加算 100単位/回（疼痛緩和のための特別な薬剤の投薬を受けている利用者）',
  },
  {
    ssot_key: 'care.addition.narcotic_continuous_injection',
    rule_type: 'addition',
    service_type: 'care_home_management',
    payer_basis: 'care',
    provider_scope: 'pharmacy',
    selection_mode: 'auto',
    calculation_unit: 'unit',
    display_order: 340,
    name: '医療用麻薬持続注射療法加算（介護）',
    code: 'CARE_ADD_NARCOTIC_INJECTION',
    amount: 250,
    conditions: {
      requires_narcotic_continuous_injection: true,
    },
    evidence_requirements: {
      narcotic_injection_management_record: true,
      high_care_medical_device_license: true,
    },
    source_url: CARE_SOURCE_URL,
    source_note: '居宅療養管理指導 医療用麻薬持続注射療法加算 250単位/回（令和6年新設。麻薬管理指導加算との併算定不可）',
  },
  {
    ssot_key: 'care.addition.central_venous_nutrition',
    rule_type: 'addition',
    service_type: 'care_home_management',
    payer_basis: 'care',
    provider_scope: 'pharmacy',
    selection_mode: 'auto',
    calculation_unit: 'unit',
    display_order: 350,
    name: '在宅中心静脈栄養法加算（介護）',
    code: 'CARE_ADD_CENTRAL_VENOUS',
    amount: 150,
    conditions: {
      requires_central_venous_nutrition: true,
    },
    evidence_requirements: {
      central_venous_management_record: true,
      high_care_medical_device_license: true,
    },
    source_url: CARE_SOURCE_URL,
    source_note: '居宅療養管理指導 在宅中心静脈栄養法加算 150単位/回（令和6年新設）',
  },
];
