import type { BillingRevision, BillingRuleSeed } from './types';

export const MEDICAL_REVISION: BillingRevision = {
  code: '2024',
  label: '令和6年度 診療報酬改定',
  effectiveFrom: new Date('2024-06-01'),
  effectiveTo: null,
  source: 'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000188411_00045.html',
};

const MEDICAL_SOURCE_URL =
  'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000188411_00045.html';
const MEDICAL_TABLE_URL = 'https://www.mhlw.go.jp/content/12404000/001218733.pdf';

export const MEDICAL_RULES_2024: BillingRuleSeed[] = [
  {
    ssot_key: 'medical.home_visit.single',
    rule_type: 'base',
    service_type: 'medical_home_visit',
    payer_basis: 'medical',
    provider_scope: 'pharmacy',
    selection_mode: 'auto',
    calculation_unit: 'point',
    display_order: 10,
    name: '在宅患者訪問薬剤管理指導料 単一建物1人',
    code: 'MED_HOME_VISIT_SINGLE',
    amount: 650,
    conditions: {
      building_tier: 'single',
      monthly_cap: 4,
      weekly_pharmacist_cap: 40,
      special_monthly_cap: 8,
      special_weekly_cap: 2,
    },
    evidence_requirements: {
      requires_physician_instruction: true,
      requires_management_plan: true,
      requires_visit_documentation: true,
      requires_written_report: true,
    },
    source_url: MEDICAL_TABLE_URL,
    source_note: `厚労省 令和6年度診療報酬改定 在宅患者訪問薬剤管理指導料（単一建物1人 ${650}点）`,
  },
  {
    ssot_key: 'medical.home_visit.multi_2_9',
    rule_type: 'base',
    service_type: 'medical_home_visit',
    payer_basis: 'medical',
    provider_scope: 'pharmacy',
    selection_mode: 'auto',
    calculation_unit: 'point',
    display_order: 20,
    name: '在宅患者訪問薬剤管理指導料 単一建物2〜9人',
    code: 'MED_HOME_VISIT_MULTI_2_9',
    amount: 320,
    conditions: {
      building_tier: 'multi_2_9',
      monthly_cap: 4,
      weekly_pharmacist_cap: 40,
      special_monthly_cap: 8,
      special_weekly_cap: 2,
    },
    evidence_requirements: {
      requires_physician_instruction: true,
      requires_management_plan: true,
      requires_visit_documentation: true,
      requires_written_report: true,
    },
    source_url: MEDICAL_TABLE_URL,
    source_note: `厚労省 令和6年度診療報酬改定 在宅患者訪問薬剤管理指導料（単一建物2〜9人 ${320}点）`,
  },
  {
    ssot_key: 'medical.home_visit.multi_10_plus',
    rule_type: 'base',
    service_type: 'medical_home_visit',
    payer_basis: 'medical',
    provider_scope: 'pharmacy',
    selection_mode: 'auto',
    calculation_unit: 'point',
    display_order: 30,
    name: '在宅患者訪問薬剤管理指導料 単一建物10人以上',
    code: 'MED_HOME_VISIT_MULTI_10_PLUS',
    amount: 290,
    conditions: {
      building_tier: 'multi_10_plus',
      monthly_cap: 4,
      weekly_pharmacist_cap: 40,
      special_monthly_cap: 8,
      special_weekly_cap: 2,
    },
    evidence_requirements: {
      requires_physician_instruction: true,
      requires_management_plan: true,
      requires_visit_documentation: true,
      requires_written_report: true,
    },
    source_url: MEDICAL_TABLE_URL,
    source_note: `厚労省 令和6年度診療報酬改定 在宅患者訪問薬剤管理指導料（単一建物10人以上 ${290}点）`,
  },
  {
    ssot_key: 'medical.home_visit.online',
    rule_type: 'base',
    service_type: 'medical_home_visit',
    payer_basis: 'medical',
    provider_scope: 'pharmacy',
    selection_mode: 'manual',
    calculation_unit: 'point',
    display_order: 40,
    name: '在宅患者オンライン薬剤管理指導料',
    code: 'MED_HOME_VISIT_ONLINE',
    amount: 59,
    conditions: {
      requires_online_visit: true,
      monthly_cap_shared: true,
      weekly_pharmacist_cap: 40,
    },
    source_url: MEDICAL_SOURCE_URL,
    source_note: '厚労省 令和6年度診療報酬改定 在宅患者オンライン薬剤管理指導料 59点',
  },
  {
    ssot_key: 'medical.addition.narcotic',
    rule_type: 'addition',
    service_type: 'medical_home_visit',
    payer_basis: 'medical',
    provider_scope: 'pharmacy',
    selection_mode: 'manual',
    calculation_unit: 'point',
    display_order: 100,
    name: '麻薬管理指導加算',
    code: 'MED_ADD_NARCOTIC',
    amount: 100,
    conditions: {
      requires_narcotic_management: true,
    },
    source_url: MEDICAL_SOURCE_URL,
    source_note: '厚労省 令和6年度診療報酬改定 麻薬管理指導加算 100点',
  },
  {
    ssot_key: 'medical.addition.narcotic_online',
    rule_type: 'addition',
    service_type: 'medical_home_visit',
    payer_basis: 'medical',
    provider_scope: 'pharmacy',
    selection_mode: 'manual',
    calculation_unit: 'point',
    display_order: 110,
    name: '麻薬管理指導加算（オンライン）',
    code: 'MED_ADD_NARCOTIC_ONLINE',
    amount: 22,
    conditions: {
      requires_online_visit: true,
      requires_narcotic_management: true,
    },
    source_url: MEDICAL_SOURCE_URL,
    source_note: '厚労省 令和6年度診療報酬改定 麻薬管理指導加算（オンライン）22点',
  },
  {
    ssot_key: 'medical.addition.continuous_narcotic_infusion',
    rule_type: 'addition',
    service_type: 'medical_home_visit',
    payer_basis: 'medical',
    provider_scope: 'pharmacy',
    selection_mode: 'manual',
    calculation_unit: 'point',
    display_order: 120,
    name: '在宅患者医療用麻薬持続注射療法加算',
    code: 'MED_ADD_CONTINUOUS_NARCOTIC',
    amount: 250,
    conditions: {
      requires_continuous_narcotic_infusion: true,
      special_cap_eligible: true,
    },
    source_url: MEDICAL_SOURCE_URL,
    source_note: '厚労省 令和6年度診療報酬改定 在宅患者医療用麻薬持続注射療法加算 250点',
  },
  {
    ssot_key: 'medical.addition.infant',
    rule_type: 'addition',
    service_type: 'medical_home_visit',
    payer_basis: 'medical',
    provider_scope: 'pharmacy',
    selection_mode: 'manual',
    calculation_unit: 'point',
    display_order: 130,
    name: '乳幼児加算',
    code: 'MED_ADD_INFANT',
    amount: 100,
    conditions: {
      requires_infant_eligibility: true,
    },
    source_url: MEDICAL_SOURCE_URL,
    source_note: '厚労省 令和6年度診療報酬改定 乳幼児加算 100点',
  },
  {
    ssot_key: 'medical.addition.infant_online',
    rule_type: 'addition',
    service_type: 'medical_home_visit',
    payer_basis: 'medical',
    provider_scope: 'pharmacy',
    selection_mode: 'manual',
    calculation_unit: 'point',
    display_order: 140,
    name: '乳幼児加算（オンライン）',
    code: 'MED_ADD_INFANT_ONLINE',
    amount: 12,
    conditions: {
      requires_online_visit: true,
      requires_infant_eligibility: true,
    },
    source_url: MEDICAL_SOURCE_URL,
    source_note: '厚労省 令和6年度診療報酬改定 乳幼児加算（オンライン）12点',
  },
  {
    ssot_key: 'medical.addition.pediatric_special',
    rule_type: 'addition',
    service_type: 'medical_home_visit',
    payer_basis: 'medical',
    provider_scope: 'pharmacy',
    selection_mode: 'manual',
    calculation_unit: 'point',
    display_order: 150,
    name: '小児特定加算',
    code: 'MED_ADD_PEDIATRIC_SPECIAL',
    amount: 450,
    conditions: {
      requires_pediatric_special_eligibility: true,
    },
    source_url: MEDICAL_SOURCE_URL,
    source_note: '厚労省 令和6年度診療報酬改定 小児特定加算 450点',
  },
  {
    ssot_key: 'medical.information_provision.1',
    rule_type: 'addition',
    service_type: 'generic',
    payer_basis: 'medical',
    provider_scope: 'pharmacy',
    selection_mode: 'manual',
    calculation_unit: 'point',
    display_order: 400,
    name: '服薬情報等提供料1',
    code: 'MED_INFO_PROVISION_1',
    amount: 30,
    conditions: {
      information_provision_type: '1',
      requested_by_medical_institution: true,
      frequency_limit: 'monthly_once',
    },
    source_url: MEDICAL_TABLE_URL,
    source_note: '調剤報酬点数表 区分15の5 服薬情報等提供料1 30点',
  },
  {
    ssot_key: 'medical.information_provision.2_medical',
    rule_type: 'addition',
    service_type: 'generic',
    payer_basis: 'medical',
    provider_scope: 'pharmacy',
    selection_mode: 'manual',
    calculation_unit: 'point',
    display_order: 410,
    name: '服薬情報等提供料2 イ',
    code: 'MED_INFO_PROVISION_2_I',
    amount: 20,
    conditions: {
      information_provision_type: '2_i',
      target: 'medical_institution',
      frequency_limit: 'monthly_once',
    },
    source_url: MEDICAL_TABLE_URL,
    source_note: '調剤報酬点数表 区分15の5 服薬情報等提供料2 イ 20点',
  },
  {
    ssot_key: 'medical.information_provision.2_refill',
    rule_type: 'addition',
    service_type: 'generic',
    payer_basis: 'medical',
    provider_scope: 'pharmacy',
    selection_mode: 'manual',
    calculation_unit: 'point',
    display_order: 420,
    name: '服薬情報等提供料2 ロ',
    code: 'MED_INFO_PROVISION_2_RO',
    amount: 20,
    conditions: {
      information_provision_type: '2_ro',
      target: 'prescriber',
      refill_followup: true,
      frequency_limit: 'monthly_once',
    },
    source_url: MEDICAL_TABLE_URL,
    source_note: '調剤報酬点数表 区分15の5 服薬情報等提供料2 ロ 20点',
  },
  {
    ssot_key: 'medical.information_provision.2_care_manager',
    rule_type: 'addition',
    service_type: 'generic',
    payer_basis: 'medical',
    provider_scope: 'pharmacy',
    selection_mode: 'manual',
    calculation_unit: 'point',
    display_order: 430,
    name: '服薬情報等提供料2 ハ',
    code: 'MED_INFO_PROVISION_2_HA',
    amount: 20,
    conditions: {
      information_provision_type: '2_ha',
      target: 'care_manager',
      same_month_home_management_disallowed: true,
      frequency_limit: 'monthly_once',
    },
    source_url: MEDICAL_TABLE_URL,
    source_note: '調剤報酬点数表 区分15の5 服薬情報等提供料2 ハ 20点',
  },
  {
    ssot_key: 'medical.information_provision.3',
    rule_type: 'addition',
    service_type: 'generic',
    payer_basis: 'medical',
    provider_scope: 'pharmacy',
    selection_mode: 'manual',
    calculation_unit: 'point',
    display_order: 440,
    name: '服薬情報等提供料3',
    code: 'MED_INFO_PROVISION_3',
    amount: 50,
    conditions: {
      information_provision_type: '3',
      pre_admission_medication_reconciliation: true,
    },
    source_url: MEDICAL_TABLE_URL,
    source_note: '調剤報酬点数表 区分15の5 服薬情報等提供料3 50点',
  },
  {
    ssot_key: 'medical.home_duplicate_interaction.change_other',
    rule_type: 'addition',
    service_type: 'generic',
    payer_basis: 'medical',
    provider_scope: 'pharmacy',
    selection_mode: 'manual',
    calculation_unit: 'point',
    display_order: 450,
    name: '在宅患者重複投薬・相互作用等防止管理料1 イ',
    code: 'MED_HOME_DUPLICATE_CHANGE_OTHER',
    amount: 40,
    conditions: {
      duplicate_interaction_type: '1_i',
      residual_adjustment: false,
      requires_prescription_change: true,
    },
    source_url: MEDICAL_TABLE_URL,
    source_note: '調剤報酬点数表 区分15の6 在宅患者重複投薬・相互作用等防止管理料1 イ 40点',
  },
  {
    ssot_key: 'medical.home_duplicate_interaction.change_residual',
    rule_type: 'addition',
    service_type: 'generic',
    payer_basis: 'medical',
    provider_scope: 'pharmacy',
    selection_mode: 'manual',
    calculation_unit: 'point',
    display_order: 460,
    name: '在宅患者重複投薬・相互作用等防止管理料1 ロ',
    code: 'MED_HOME_DUPLICATE_CHANGE_RESIDUAL',
    amount: 20,
    conditions: {
      duplicate_interaction_type: '1_ro',
      residual_adjustment: true,
      requires_prescription_change: true,
    },
    source_url: MEDICAL_TABLE_URL,
    source_note: '調剤報酬点数表 区分15の6 在宅患者重複投薬・相互作用等防止管理料1 ロ 20点',
  },
  {
    ssot_key: 'medical.home_duplicate_interaction.proposal_other',
    rule_type: 'addition',
    service_type: 'generic',
    payer_basis: 'medical',
    provider_scope: 'pharmacy',
    selection_mode: 'manual',
    calculation_unit: 'point',
    display_order: 470,
    name: '在宅患者重複投薬・相互作用等防止管理料2 イ',
    code: 'MED_HOME_DUPLICATE_PROPOSAL_OTHER',
    amount: 40,
    conditions: {
      duplicate_interaction_type: '2_i',
      residual_adjustment: false,
      proposal_reflected: true,
    },
    source_url: MEDICAL_TABLE_URL,
    source_note: '調剤報酬点数表 区分15の6 在宅患者重複投薬・相互作用等防止管理料2 イ 40点',
  },
  {
    ssot_key: 'medical.home_duplicate_interaction.proposal_residual',
    rule_type: 'addition',
    service_type: 'generic',
    payer_basis: 'medical',
    provider_scope: 'pharmacy',
    selection_mode: 'manual',
    calculation_unit: 'point',
    display_order: 480,
    name: '在宅患者重複投薬・相互作用等防止管理料2 ロ',
    code: 'MED_HOME_DUPLICATE_PROPOSAL_RESIDUAL',
    amount: 20,
    conditions: {
      duplicate_interaction_type: '2_ro',
      residual_adjustment: true,
      proposal_reflected: true,
    },
    source_url: MEDICAL_TABLE_URL,
    source_note: '調剤報酬点数表 区分15の6 在宅患者重複投薬・相互作用等防止管理料2 ロ 20点',
  },
  // ── 在宅患者緊急訪問薬剤管理指導料（令和6年度） ──
  // 介護認定の有無に関わらず医療保険で算定。
  // 1: 計画的訪問の対象疾患の急変 500点
  // 2: それ以外の急変 200点
  {
    ssot_key: 'medical.emergency_visit.1',
    rule_type: 'base',
    service_type: 'medical_home_visit',
    payer_basis: 'medical',
    provider_scope: 'pharmacy',
    selection_mode: 'auto',
    calculation_unit: 'point',
    display_order: 500,
    name: '在宅患者緊急訪問薬剤管理指導料1',
    code: 'MED_EMERGENCY_VISIT_1',
    amount: 500,
    conditions: {
      visit_type: 'emergency',
      emergency_category: 'planned_disease_exacerbation',
      monthly_cap: 4,
    },
    source_url: MEDICAL_TABLE_URL,
    source_note: '調剤報酬点数表 区分15の3 在宅患者緊急訪問薬剤管理指導料1 500点（計画的訪問の対象疾患の急変）',
  },
  {
    ssot_key: 'medical.emergency_visit.2',
    rule_type: 'base',
    service_type: 'medical_home_visit',
    payer_basis: 'medical',
    provider_scope: 'pharmacy',
    selection_mode: 'auto',
    calculation_unit: 'point',
    display_order: 510,
    name: '在宅患者緊急訪問薬剤管理指導料2',
    code: 'MED_EMERGENCY_VISIT_2',
    amount: 200,
    conditions: {
      visit_type: 'emergency',
      emergency_category: 'other_exacerbation',
      monthly_cap: 4,
    },
    source_url: MEDICAL_TABLE_URL,
    source_note: '調剤報酬点数表 区分15の3 在宅患者緊急訪問薬剤管理指導料2 200点（それ以外の急変）',
  },
  {
    ssot_key: 'medical.emergency_visit.online',
    rule_type: 'base',
    service_type: 'medical_home_visit',
    payer_basis: 'medical',
    provider_scope: 'pharmacy',
    selection_mode: 'auto',
    calculation_unit: 'point',
    display_order: 520,
    name: '在宅患者緊急オンライン薬剤管理指導料',
    code: 'MED_EMERGENCY_VISIT_ONLINE',
    amount: 59,
    conditions: {
      visit_type: 'emergency',
      emergency_category: 'online',
      monthly_cap: 4,
    },
    source_url: MEDICAL_TABLE_URL,
    source_note: '調剤報酬点数表 区分15の3 在宅患者緊急オンライン薬剤管理指導料 59点',
  },
];
