export const WORKFLOW_DASHBOARD_INVALIDATION_SOURCES = [
  'schedule_conflict_resolution',
  'cycle_holds_create',
  'cycle_holds_resolve',
  'dispense_audits',
  'dispense_results',
  'dispense_results_rework',
  'dispense_tasks_update',
  'facility_visit_batch_delete',
  'facility_visit_batch_reorder',
  'facility_visit_batches_upsert',
  'facility_visit_days_upsert',
  'inquiry_records_update',
  'medication_cycles_transition',
  'medication_issues_update',
  'prescription_intakes_create',
  'set_audits',
  'set_batches_create',
  'set_batches_delete',
  'set_batches_generate',
  'set_batches_update',
  'set_plans',
  'set_plans_update',
  'visit_schedule_proposals_approve',
  'visit_schedule_proposals_confirm',
  'visit_schedule_proposals_contact_attempt',
  'visit_schedule_proposals_create',
  'visit_schedule_proposals_reject',
  'visit_schedule_proposals_reorder',
  'visit_preparations_update',
  'visit_routes_mixed_reorder',
  'visit_schedule_conflict_reconfirmation',
  'visit_schedules_create',
  'visit_schedules_delete',
  'visit_schedules_generate',
  'visit_schedules_reopen',
  'visit_schedules_reorder',
  'visit_schedules_reschedule_approve',
  'visit_schedules_reschedule_request',
  'visit_schedules_update',
] as const;

export const WORKFLOW_DASHBOARD_INVALIDATION_EVENTS = [
  'cycle_transition',
  { type: 'workflow_refresh', source: WORKFLOW_DASHBOARD_INVALIDATION_SOURCES },
] as const;

export const SCHEDULE_WORKFLOW_INVALIDATION_SOURCES = [
  'visit_schedules_create',
  'visit_schedules_update',
  'visit_schedules_delete',
  'visit_schedules_reschedule_request',
  'visit_schedules_reschedule_approve',
  'visit_schedules_reopen',
  'visit_schedules_reorder',
  'visit_schedule_conflict_reconfirmation',
  'visit_schedule_proposals_create',
  'visit_schedule_proposals_approve',
  'visit_schedule_proposals_reject',
  'visit_schedule_proposals_contact_attempt',
  'visit_schedule_proposals_confirm',
  'visit_schedule_proposals_reorder',
  'facility_visit_batches_upsert',
  'facility_visit_batch_delete',
  'facility_visit_batch_reorder',
  'facility_visit_days_upsert',
] as const;

export const SCHEDULE_WORKFLOW_INVALIDATION_EVENTS = [
  { type: 'workflow_refresh', source: SCHEDULE_WORKFLOW_INVALIDATION_SOURCES },
] as const;
