import type { Prisma } from '@prisma/client';
import {
  buildAssignedCareCaseWhere,
  type PatientDetailScopeArgs,
} from '@/server/services/patient-detail-scope';

export const PATIENT_OVERVIEW_RELATION_LIMITS = {
  residences: 4,
  contacts: 12,
  conditions: 12,
  consents: 8,
  cases: 8,
  careTeamLinks: 12,
} as const;

export function buildPatientOverviewBaseSelect(args: PatientDetailScopeArgs) {
  const assignedCareCaseWhere = buildAssignedCareCaseWhere(args);

  return {
    id: true,
    display_id: true,
    name: true,
    name_kana: true,
    birth_date: true,
    gender: true,
    phone: true,
    medical_insurance_number: true,
    care_insurance_number: true,
    billing_support_flag: true,
    primary_pharmacist_id: true,
    backup_pharmacist_id: true,
    primary_staff_id: true,
    backup_staff_id: true,
    allergy_info: true,
    notes: true,
    archived_at: true,
    archived_by: true,
    created_at: true,
    updated_at: true,
    residences: {
      where: { org_id: args.orgId },
      orderBy: [{ is_primary: 'desc' }, { created_at: 'asc' }, { id: 'asc' }],
      take: PATIENT_OVERVIEW_RELATION_LIMITS.residences,
      select: {
        id: true,
        address: true,
        building_id: true,
        facility_id: true,
        facility_unit_id: true,
        unit_name: true,
        is_primary: true,
      },
    },
    scheduling_preference: {
      select: {
        preferred_weekdays: true,
        preferred_time_from: true,
        preferred_time_to: true,
        phone_contact_from: true,
        phone_contact_to: true,
        facility_time_from: true,
        facility_time_to: true,
        family_presence_required: true,
        visit_buffer_minutes: true,
        preferred_contact_name: true,
        preferred_contact_phone: true,
        visit_before_contact_required: true,
        first_visit_preferred_date: true,
        first_visit_time_slot: true,
        first_visit_time_note: true,
        parking_available: true,
        primary_contact_preference: true,
        mcs_linked: true,
        adl_level: true,
        dementia_level: true,
        swallowing_route: true,
        care_level: true,
        infection_isolation: true,
      },
    },
    contacts: {
      where: { org_id: args.orgId },
      orderBy: [
        { is_primary: 'desc' },
        { is_emergency_contact: 'desc' },
        { created_at: 'asc' },
        { id: 'asc' },
      ],
      take: PATIENT_OVERVIEW_RELATION_LIMITS.contacts,
      select: {
        id: true,
        relation: true,
        name: true,
        phone: true,
        email: true,
        fax: true,
        organization_name: true,
        department: true,
        address: true,
        is_primary: true,
        is_emergency_contact: true,
        notes: true,
      },
    },
    conditions: {
      where: { org_id: args.orgId },
      orderBy: [
        { is_active: 'desc' },
        { is_primary: 'desc' },
        { noted_at: 'desc' },
        { created_at: 'desc' },
        { id: 'asc' },
      ],
      take: PATIENT_OVERVIEW_RELATION_LIMITS.conditions,
      select: {
        id: true,
        condition_type: true,
        name: true,
        is_primary: true,
        is_active: true,
        noted_at: true,
        notes: true,
      },
    },
    consents: {
      where: {
        org_id: args.orgId,
        OR: [{ is_active: true }, { revoked_date: { not: null } }],
      },
      orderBy: [
        { is_active: 'desc' },
        { obtained_date: 'desc' },
        { created_at: 'desc' },
        { id: 'desc' },
      ],
      take: PATIENT_OVERVIEW_RELATION_LIMITS.consents,
      select: {
        id: true,
        case_id: true,
        template_id: true,
        template_version: true,
        consent_type: true,
        method: true,
        obtained_date: true,
        expiry_date: true,
        revoked_date: true,
        is_active: true,
        access_restricted: true,
        created_at: true,
        updated_at: true,
      },
    },
    cases: {
      where: {
        org_id: args.orgId,
        ...(assignedCareCaseWhere ?? {}),
      },
      orderBy: [{ updated_at: 'desc' }, { created_at: 'desc' }, { id: 'desc' }],
      take: PATIENT_OVERVIEW_RELATION_LIMITS.cases,
      select: {
        id: true,
        display_id: true,
        status: true,
        referral_source: true,
        referral_date: true,
        start_date: true,
        end_date: true,
        end_reason: true,
        primary_pharmacist_id: true,
        backup_pharmacist_id: true,
        primary_staff_id: true,
        backup_staff_id: true,
        required_visit_support: true,
        notes: true,
        created_at: true,
        updated_at: true,
        care_team_links: {
          where: { org_id: args.orgId },
          orderBy: [{ is_primary: 'desc' }, { created_at: 'asc' }, { id: 'asc' }],
          take: PATIENT_OVERVIEW_RELATION_LIMITS.careTeamLinks,
          select: {
            id: true,
            external_professional_id: true,
            role: true,
            name: true,
            organization_name: true,
            department: true,
            phone: true,
            email: true,
            fax: true,
            address: true,
            is_primary: true,
            notes: true,
          },
        },
      },
    },
  } satisfies Prisma.PatientSelect;
}
