export const STABLE_PATIENT_BOARD_RESPONSE = {
  data: [
    {
      patient_id: 'preview_patient_a',
      name: 'テスト患者A',
      age: 80,
      residence_kind: 'home',
      residence_label: '在宅',
      attention: 'urgent_now',
      safety_tags: ['renal'],
      next_visit_date: '2026-07-12',
      next_visit_time: '10:00',
      next_visit_label: null,
      current_step: 'audit',
      status_text: '監査前の確認が必要です',
      status_tone: 'critical',
      operation_summary: ['連絡先あり'],
      foundation_summary: {
        status: 'ready',
        label: '情報確認済み',
        items: ['連絡先あり'],
      },
      foundation_issue_keys: [],
      foundation_href: '/patients/preview_patient_a#patient-foundation',
      link_label: '監査へ',
      link_href: '/audit',
    },
    {
      patient_id: 'preview_patient_b',
      name: 'テスト患者B',
      age: 81,
      residence_kind: 'facility',
      residence_label: '施設',
      attention: 'external_wait',
      safety_tags: [],
      next_visit_date: null,
      next_visit_time: null,
      next_visit_label: '日程調整中',
      current_step: 'decision',
      status_text: '外部からの回答を待っています',
      status_tone: 'external',
      operation_summary: [],
      foundation_summary: {
        status: 'ready',
        label: '情報確認済み',
        items: [],
      },
      foundation_issue_keys: [],
      foundation_href: '/patients/preview_patient_b#patient-foundation',
      link_label: '連携を確認',
      link_href: '/communications/requests',
    },
    {
      patient_id: 'preview_patient_c',
      name: 'テスト患者C',
      age: 76,
      residence_kind: 'home',
      residence_label: '在宅',
      attention: 'urgent_now',
      safety_tags: [],
      next_visit_date: '2026-07-13',
      next_visit_time: '14:00',
      next_visit_label: null,
      current_step: 'audit',
      status_text: '監査前の確認が必要です',
      status_tone: 'critical',
      operation_summary: ['連絡先あり'],
      foundation_summary: {
        status: 'ready',
        label: '情報確認済み',
        items: ['連絡先あり'],
      },
      foundation_issue_keys: [],
      foundation_href: '/patients/preview_patient_c#patient-foundation',
      link_label: '監査へ',
      link_href: '/audit',
    },
    {
      patient_id: 'preview_patient_d',
      name: 'テスト患者D',
      age: 88,
      residence_kind: 'facility',
      residence_label: '施設',
      attention: 'external_wait',
      safety_tags: ['renal'],
      next_visit_date: null,
      next_visit_time: null,
      next_visit_label: '日程調整中',
      current_step: 'decision',
      status_text: '外部からの回答を待っています',
      status_tone: 'external',
      operation_summary: [],
      foundation_summary: {
        status: 'ready',
        label: '情報確認済み',
        items: [],
      },
      foundation_issue_keys: [],
      foundation_href: '/patients/preview_patient_d#patient-foundation',
      link_label: '連携を確認',
      link_href: '/communications/requests',
    },
  ],
  meta: {
    generated_at: '2026-07-11T12:00:00.000Z',
    scope: 'mine',
    limit: 60,
    returned_count: 4,
    has_more: false,
    next_cursor: null,
    total_count: 4,
    count_basis: {
      total_count: 'filtered_result_exact',
      chip_counts: 'scope_search_foundation_exact',
      foundation_issue_counts: 'scope_search_without_active_foundation_issue_exact',
      board_summary: 'scope_search_foundation_exact',
    },
    filters_applied: {
      scope: 'mine',
      q_present: false,
      foundation_issue: null,
      card_filter: 'all',
      sort: 'priority',
    },
    facets: {
      chip_counts: { urgent_now: 2, external_wait: 2, visit_today: 0, paused: 0 },
      foundation_issue_counts: {
        needs_confirmation: 0,
        missing_contact: 0,
        missing_consent_plan: 0,
        missing_parking: 0,
        missing_care_level: 0,
        missing_insurance: 0,
        missing_care_team: 0,
      },
      today_facility_patient_count: 0,
      today_visit_count: 0,
      safety_tagged_count: 2,
    },
    rail: { next_action: null, blocked_reasons: [] },
    assigned_total: 4,
  },
} as const;
