export const PATH_LABELS: Array<{ pattern: RegExp; label: string }> = [
  { pattern: /^\/dashboard$/, label: 'ホーム' },
  { pattern: /^\/my-day(\/.*)?$/, label: 'My Day' },
  { pattern: /^\/workflow(\/.*)?$/, label: 'ワークフロー' },
  { pattern: /^\/tasks(\/.*)?$/, label: 'タスク' },
  { pattern: /^\/communications\/requests(\/.*)?$/, label: '依頼・照会' },
  { pattern: /^\/billing\/candidates(\/.*)?$/, label: '請求候補' },
  { pattern: /^\/billing(\/.*)?$/, label: '請求' },
  { pattern: /^\/patients\/new$/, label: '患者新規登録' },
  { pattern: /^\/patients\/[^/]+\/edit$/, label: '患者情報編集' },
  { pattern: /^\/patients\/[^/]+\/mcs(\/.*)?$/, label: 'MCS連携' },
  { pattern: /^\/patients(\/.*)?$/, label: '患者' },
  { pattern: /^\/prescriptions\/qr-drafts(\/.*)?$/, label: 'QR下書き' },
  { pattern: /^\/prescriptions\/new(\/.*)?$/, label: '新規処方受付' },
  { pattern: /^\/prescriptions(\/.*)?$/, label: '処方受付' },
  { pattern: /^\/qr-scan(\/.*)?$/, label: 'QRスキャン' },
  { pattern: /^\/schedules\/proposals(\/.*)?$/, label: '提案一覧' },
  { pattern: /^\/schedules\/route-compare(\/.*)?$/, label: 'ルート案を比べる' },
  { pattern: /^\/schedules(\/.*)?$/, label: 'スケジュール' },
  { pattern: /^\/visits(\/.*)?$/, label: '訪問' },
  { pattern: /^\/reports\/analytics(\/.*)?$/, label: '送達分析' },
  { pattern: /^\/reports(\/.*)?$/, label: '報告' },
  { pattern: /^\/dispensing(\/.*)?$/, label: '調剤' },
  { pattern: /^\/auditing(\/.*)?$/, label: '鑑査' },
  { pattern: /^\/medication-sets(\/.*)?$/, label: 'セット' },
  { pattern: /^\/conferences(\/.*)?$/, label: '多職種連携' },
  { pattern: /^\/handoff(\/.*)?$/, label: '申し送り' },
  { pattern: /^\/external(\/.*)?$/, label: '外部連携' },
  { pattern: /^\/notifications(\/.*)?$/, label: '通知' },
  { pattern: /^\/admin\/alert-rules(\/.*)?$/, label: '処方安全アラート' },
  { pattern: /^\/admin\/audit-logs(\/.*)?$/, label: '監査ログ' },
  { pattern: /^\/admin\/billing-rules(\/.*)?$/, label: '請求ルール' },
  { pattern: /^\/admin\/business-holidays(\/.*)?$/, label: '休日カレンダー' },
  { pattern: /^\/admin\/contact-profiles(\/.*)?$/, label: '連携先' },
  { pattern: /^\/admin\/data-explorer(\/.*)?$/, label: 'データ探索' },
  { pattern: /^\/admin\/document-templates(\/.*)?$/, label: '文書テンプレート' },
  { pattern: /^\/admin\/drug-masters(\/.*)?$/, label: '医薬品マスタ' },
  { pattern: /^\/admin\/facilities(\/.*)?$/, label: '施設' },
  { pattern: /^\/admin\/facility-standards(\/.*)?$/, label: '施設基準' },
  { pattern: /^\/admin\/formulary(\/.*)?$/, label: '採用薬' },
  { pattern: /^\/admin\/institutions(\/.*)?$/, label: '医療機関' },
  { pattern: /^\/admin\/inventory-forecast(\/.*)?$/, label: '在庫と定期処方の予測' },
  { pattern: /^\/admin\/pca-pumps(\/.*)?$/, label: 'PCAポンプ' },
  { pattern: /^\/admin\/jobs(\/.*)?$/, label: 'ジョブ監視' },
  { pattern: /^\/admin\/metrics(\/.*)?$/, label: '経営指標' },
  { pattern: /^\/admin\/operations-insights(\/.*)?$/, label: '在宅業務の動きを見る' },
  { pattern: /^\/admin\/notification-settings(\/.*)?$/, label: '通知設定' },
  { pattern: /^\/admin\/performance(\/.*)?$/, label: 'パフォーマンス' },
  { pattern: /^\/admin\/analytics(\/.*)?$/, label: 'KPI分析' },
  { pattern: /^\/admin\/professionals(\/.*)?$/, label: '他職種' },
  { pattern: /^\/admin\/realtime(\/.*)?$/, label: 'リアルタイム監視' },
  { pattern: /^\/admin\/settings(\/.*)?$/, label: '管理設定' },
  { pattern: /^\/admin\/external-professionals(\/.*)?$/, label: '他職種マスター' },
  { pattern: /^\/admin\/pharmacist-credentials(\/.*)?$/, label: '薬剤師資格' },
  { pattern: /^\/admin\/pharmacy-sites(\/.*)?$/, label: '薬局情報' },
  { pattern: /^\/admin\/service-areas(\/.*)?$/, label: '訪問エリア' },
  { pattern: /^\/admin\/staff(\/.*)?$/, label: 'スタッフ' },
  { pattern: /^\/admin\/users(\/.*)?$/, label: 'ユーザー' },
  { pattern: /^\/admin(\/.*)?$/, label: '管理' },
  { pattern: /^\/settings$/, label: 'ユーザー設定' },
  { pattern: /^\/referrals\/new$/, label: '紹介受付' },
];

const SEGMENT_LABELS: Record<string, string> = {
  admin: '管理',
  'alert-rules': '処方安全アラート',
  analytics: '分析',
  audit: '監査',
  'audit-logs': '監査ログ',
  auditing: '鑑査',
  billing: '請求',
  'billing-rules': '請求ルール',
  'business-holidays': '休日カレンダー',
  candidates: '候補',
  collaboration: '今だれが見ているか',
  communications: '連携',
  conferences: '多職種連携',
  consent: '同意',
  'contact-profiles': '連携先',
  dashboard: 'ダッシュボード',
  'data-explorer': 'データ探索',
  dispensing: '調剤',
  'document-templates': '文書テンプレート',
  'drug-masters': '医薬品マスタ',
  external: '外部連携',
  'external-professionals': '他職種',
  facilities: '施設',
  'facility-standards': '施設基準',
  formulary: '採用薬',
  full: '一覧',
  handoff: '申し送り',
  institutions: '医療機関',
  'inventory-forecast': '在庫と定期処方の予測',
  jobs: 'ジョブ',
  login: 'ログイン',
  medications: '服薬中薬剤',
  'medication-calendar': '服薬カレンダー',
  'medication-sets': 'セット',
  metrics: '経営指標',
  mcs: 'MCS連携',
  'my-day': 'My Day',
  new: '新規',
  notifications: '通知',
  'notification-settings': '通知設定',
  'operations-insights': '在宅業務の動きを見る',
  patients: '患者',
  performance: '性能',
  pharmacists: '薬剤師',
  'pharmacist-credentials': '薬剤師資格',
  'pharmacy-sites': '薬局情報',
  print: '印刷',
  professionals: '他職種',
  proposals: '提案',
  'qr-drafts': 'QR下書き',
  'qr-scan': 'QRスキャン',
  realtime: 'リアルタイム',
  record: '記録入力',
  referrals: '紹介',
  reports: '報告',
  requests: '依頼・照会',
  schedules: 'スケジュール',
  'service-areas': '訪問エリア',
  settings: '設定',
  share: '共有',
  shifts: 'シフト',
  staff: 'スタッフ',
  tasks: 'タスク',
  uat: 'UAT',
  users: 'ユーザー',
  visits: '訪問',
  workflow: 'ワークフロー',
};

export function labelForPath(pathname: string) {
  return PATH_LABELS.find((item) => item.pattern.test(pathname))?.label ?? pathname;
}

export function labelForSegment(segment: string, previous?: string): string {
  if (segment === 'analytics' && previous === 'reports') return '送達分析';
  if (segment === 'prescriptions') {
    return previous === 'patients' ? '処方履歴' : '処方受付';
  }
  if (segment === 'settings' && previous === 'admin') return '管理設定';
  if (SEGMENT_LABELS[segment]) return SEGMENT_LABELS[segment];
  if (segment.startsWith('D')) return 'デザイン';
  if (!previous) return '詳細';
  if (previous === 'patients') return '患者詳細';
  if (previous === 'visits') return '訪問詳細';
  if (previous === 'reports') return '報告詳細';
  if (previous === 'dispensing') return '調剤';
  if (previous === 'auditing') return '監査';
  if (previous === 'medication-sets') return 'セット詳細';
  return '詳細';
}
