import type { BillingRevision, BillingRuleSeed } from '../../types';

export const MEDICAL_REVISION: BillingRevision = {
  code: '2024',
  label: '令和6年度 診療報酬改定',
  effectiveFrom: new Date('2024-06-01'),
  effectiveTo: null,
  source: 'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000188411_00045.html',
};

const MEDICAL_SOURCE_URL =
  'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000188411_00045.html';
const MEDICAL_TABLE_URL = 'https://www.mhlw.go.jp/content/12404000/001218733.pdf';

export const MEDICAL_RULES_2024: BillingRuleSeed[] = [
  {
    ssot_key: 'medical.home_visit.single',
    rule_type: 'base',
    service_type: 'medical_home_visit',
    payer_basis: 'medical',
    provider_scope: 'pharmacy',
    selection_mode: 'auto',
    calculation_unit: 'point',
    display_order: 10,
    name: '在宅患者訪問薬剤管理指導料 単一建物1人',
    code: 'MED_HOME_VISIT_SINGLE',
    amount: 650,
    conditions: {
      building_tier: 'single',
      monthly_cap: 4,
      weekly_pharmacist_cap: 40,
      special_monthly_cap: 8,
      special_weekly_cap: 2,
    },
    evidence_requirements: {
      requires_physician_instruction: true,
      requires_management_plan: true,
      requires_visit_documentation: true,
      requires_written_report: true,
    },
    exclusion_rules: {
      same_month_exclusive: [
        'medication_management_guidance',  // 服薬管理指導料
        'family_pharmacist_guidance',      // かかりつけ薬剤師指導料
        'family_pharmacist_comprehensive', // かかりつけ薬剤師包括管理料
      ],
      same_visit_exclusive: [
        'outpatient_medication_support_1', // 外来服薬支援料1
        'MED_INFO_PROVISION_1',           // 服薬情報等提供料
        'MED_INFO_PROVISION_2_I',
        'MED_INFO_PROVISION_2_RO',
        'MED_INFO_PROVISION_2_HA',
      ],
    },
    source_url: MEDICAL_TABLE_URL,
    source_note: `厚労省 令和6年度診療報酬改定 在宅患者訪問薬剤管理指導料（単一建物1人 ${650}点）`,
  },
  {
    ssot_key: 'medical.home_visit.multi_2_9',
    rule_type: 'base',
    service_type: 'medical_home_visit',
    payer_basis: 'medical',
    provider_scope: 'pharmacy',
    selection_mode: 'auto',
    calculation_unit: 'point',
    display_order: 20,
    name: '在宅患者訪問薬剤管理指導料 単一建物2〜9人',
    code: 'MED_HOME_VISIT_MULTI_2_9',
    amount: 320,
    conditions: {
      building_tier: 'multi_2_9',
      monthly_cap: 4,
      weekly_pharmacist_cap: 40,
      special_monthly_cap: 8,
      special_weekly_cap: 2,
    },
    evidence_requirements: {
      requires_physician_instruction: true,
      requires_management_plan: true,
      requires_visit_documentation: true,
      requires_written_report: true,
    },
    exclusion_rules: {
      same_month_exclusive: [
        'medication_management_guidance',  // 服薬管理指導料
        'family_pharmacist_guidance',      // かかりつけ薬剤師指導料
        'family_pharmacist_comprehensive', // かかりつけ薬剤師包括管理料
      ],
      same_visit_exclusive: [
        'outpatient_medication_support_1', // 外来服薬支援料1
        'MED_INFO_PROVISION_1',           // 服薬情報等提供料
        'MED_INFO_PROVISION_2_I',
        'MED_INFO_PROVISION_2_RO',
        'MED_INFO_PROVISION_2_HA',
      ],
    },
    source_url: MEDICAL_TABLE_URL,
    source_note: `厚労省 令和6年度診療報酬改定 在宅患者訪問薬剤管理指導料（単一建物2〜9人 ${320}点）`,
  },
  {
    ssot_key: 'medical.home_visit.multi_10_plus',
    rule_type: 'base',
    service_type: 'medical_home_visit',
    payer_basis: 'medical',
    provider_scope: 'pharmacy',
    selection_mode: 'auto',
    calculation_unit: 'point',
    display_order: 30,
    name: '在宅患者訪問薬剤管理指導料 単一建物10人以上',
    code: 'MED_HOME_VISIT_MULTI_10_PLUS',
    amount: 290,
    conditions: {
      building_tier: 'multi_10_plus',
      monthly_cap: 4,
      weekly_pharmacist_cap: 40,
      special_monthly_cap: 8,
      special_weekly_cap: 2,
    },
    evidence_requirements: {
      requires_physician_instruction: true,
      requires_management_plan: true,
      requires_visit_documentation: true,
      requires_written_report: true,
    },
    exclusion_rules: {
      same_month_exclusive: [
        'medication_management_guidance',  // 服薬管理指導料
        'family_pharmacist_guidance',      // かかりつけ薬剤師指導料
        'family_pharmacist_comprehensive', // かかりつけ薬剤師包括管理料
      ],
      same_visit_exclusive: [
        'outpatient_medication_support_1', // 外来服薬支援料1
        'MED_INFO_PROVISION_1',           // 服薬情報等提供料
        'MED_INFO_PROVISION_2_I',
        'MED_INFO_PROVISION_2_RO',
        'MED_INFO_PROVISION_2_HA',
      ],
    },
    source_url: MEDICAL_TABLE_URL,
    source_note: `厚労省 令和6年度診療報酬改定 在宅患者訪問薬剤管理指導料（単一建物10人以上 ${290}点）`,
  },
  {
    ssot_key: 'medical.home_visit.online',
    rule_type: 'base',
    service_type: 'medical_home_visit',
    payer_basis: 'medical',
    provider_scope: 'pharmacy',
    selection_mode: 'manual',
    calculation_unit: 'point',
    display_order: 40,
    name: '在宅患者オンライン薬剤管理指導料',
    code: 'MED_HOME_VISIT_ONLINE',
    amount: 59,
    conditions: {
      requires_online_visit: true,
      monthly_cap_shared: true,
      weekly_pharmacist_cap: 40,
    },
    exclusion_rules: {
      same_month_exclusive: [
        'medication_management_guidance',  // 服薬管理指導料
        'family_pharmacist_guidance',      // かかりつけ薬剤師指導料
        'family_pharmacist_comprehensive', // かかりつけ薬剤師包括管理料
      ],
      same_visit_exclusive: [
        'outpatient_medication_support_1', // 外来服薬支援料1
        'MED_INFO_PROVISION_1',           // 服薬情報等提供料
        'MED_INFO_PROVISION_2_I',
        'MED_INFO_PROVISION_2_RO',
        'MED_INFO_PROVISION_2_HA',
      ],
    },
    source_url: MEDICAL_SOURCE_URL,
    source_note: '厚労省 令和6年度診療報酬改定 在宅患者オンライン薬剤管理指導料 59点',
  },
  {
    ssot_key: 'medical.addition.narcotic',
    rule_type: 'addition',
    service_type: 'medical_home_visit',
    payer_basis: 'medical',
    provider_scope: 'pharmacy',
    selection_mode: 'manual',
    calculation_unit: 'point',
    display_order: 100,
    name: '麻薬管理指導加算',
    code: 'MED_ADD_NARCOTIC',
    amount: 100,
    conditions: {
      requires_narcotic_management: true,
      exclusive_with: ['MED_ADD_CONTINUOUS_NARCOTIC'],
    },
    source_url: MEDICAL_SOURCE_URL,
    source_note: '厚労省 令和6年度診療報酬改定 麻薬管理指導加算 100点',
  },
  {
    ssot_key: 'medical.addition.narcotic_online',
    rule_type: 'addition',
    service_type: 'medical_home_visit',
    payer_basis: 'medical',
    provider_scope: 'pharmacy',
    selection_mode: 'manual',
    calculation_unit: 'point',
    display_order: 110,
    name: '麻薬管理指導加算（オンライン）',
    code: 'MED_ADD_NARCOTIC_ONLINE',
    amount: 22,
    conditions: {
      requires_online_visit: true,
      requires_narcotic_management: true,
    },
    source_url: MEDICAL_SOURCE_URL,
    source_note: '厚労省 令和6年度診療報酬改定 麻薬管理指導加算（オンライン）22点',
  },
  {
    ssot_key: 'medical.addition.continuous_narcotic_infusion',
    rule_type: 'addition',
    service_type: 'medical_home_visit',
    payer_basis: 'medical',
    provider_scope: 'pharmacy',
    selection_mode: 'manual',
    calculation_unit: 'point',
    display_order: 120,
    name: '在宅患者医療用麻薬持続注射療法加算',
    code: 'MED_ADD_CONTINUOUS_NARCOTIC',
    amount: 250,
    conditions: {
      requires_narcotic_continuous_injection: true,
      special_cap_eligible: true,
      exclusive_with: ['MED_ADD_NARCOTIC'],
    },
    source_url: MEDICAL_SOURCE_URL,
    source_note: '厚労省 令和6年度診療報酬改定 在宅患者医療用麻薬持続注射療法加算 250点',
  },
  {
    ssot_key: 'medical.addition.infant',
    rule_type: 'addition',
    service_type: 'medical_home_visit',
    payer_basis: 'medical',
    provider_scope: 'pharmacy',
    selection_mode: 'manual',
    calculation_unit: 'point',
    display_order: 130,
    name: '乳幼児加算',
    code: 'MED_ADD_INFANT',
    amount: 100,
    conditions: {
      requires_infant_eligibility: true,
    },
    source_url: MEDICAL_SOURCE_URL,
    source_note: '厚労省 令和6年度診療報酬改定 乳幼児加算 100点',
  },
  {
    ssot_key: 'medical.addition.infant_online',
    rule_type: 'addition',
    service_type: 'medical_home_visit',
    payer_basis: 'medical',
    provider_scope: 'pharmacy',
    selection_mode: 'manual',
    calculation_unit: 'point',
    display_order: 140,
    name: '乳幼児加算（オンライン）',
    code: 'MED_ADD_INFANT_ONLINE',
    amount: 12,
    conditions: {
      requires_online_visit: true,
      requires_infant_eligibility: true,
    },
    source_url: MEDICAL_SOURCE_URL,
    source_note: '厚労省 令和6年度診療報酬改定 乳幼児加算（オンライン）12点',
  },
  {
    ssot_key: 'medical.addition.pediatric_special',
    rule_type: 'addition',
    service_type: 'medical_home_visit',
    payer_basis: 'medical',
    provider_scope: 'pharmacy',
    selection_mode: 'manual',
    calculation_unit: 'point',
    display_order: 150,
    name: '小児特定加算',
    code: 'MED_ADD_PEDIATRIC_SPECIAL',
    amount: 450,
    conditions: {
      requires_pediatric_special_eligibility: true,
    },
    source_url: MEDICAL_SOURCE_URL,
    source_note: '厚労省 令和6年度診療報酬改定 小児特定加算 450点',
  },
  {
    ssot_key: 'medical.information_provision.1',
    rule_type: 'addition',
    service_type: 'generic',
    payer_basis: 'medical',
    provider_scope: 'pharmacy',
    selection_mode: 'manual',
    calculation_unit: 'point',
    display_order: 400,
    name: '服薬情報等提供料1',
    code: 'MED_INFO_PROVISION_1',
    amount: 30,
    conditions: {
      information_provision_type: '1',
      requested_by_medical_institution: true,
      frequency_limit: 'monthly_once',
    },
    source_url: MEDICAL_TABLE_URL,
    source_note: '調剤報酬点数表 区分15の5 服薬情報等提供料1 30点',
  },
  {
    ssot_key: 'medical.information_provision.2_medical',
    rule_type: 'addition',
    service_type: 'generic',
    payer_basis: 'medical',
    provider_scope: 'pharmacy',
    selection_mode: 'manual',
    calculation_unit: 'point',
    display_order: 410,
    name: '服薬情報等提供料2 イ',
    code: 'MED_INFO_PROVISION_2_I',
    amount: 20,
    conditions: {
      information_provision_type: '2_i',
      target: 'medical_institution',
      frequency_limit: 'monthly_once',
    },
    source_url: MEDICAL_TABLE_URL,
    source_note: '調剤報酬点数表 区分15の5 服薬情報等提供料2 イ 20点',
  },
  {
    ssot_key: 'medical.information_provision.2_refill',
    rule_type: 'addition',
    service_type: 'generic',
    payer_basis: 'medical',
    provider_scope: 'pharmacy',
    selection_mode: 'manual',
    calculation_unit: 'point',
    display_order: 420,
    name: '服薬情報等提供料2 ロ',
    code: 'MED_INFO_PROVISION_2_RO',
    amount: 20,
    conditions: {
      information_provision_type: '2_ro',
      target: 'prescriber',
      refill_followup: true,
      frequency_limit: 'monthly_once',
    },
    source_url: MEDICAL_TABLE_URL,
    source_note: '調剤報酬点数表 区分15の5 服薬情報等提供料2 ロ 20点',
  },
  {
    ssot_key: 'medical.information_provision.2_care_manager',
    rule_type: 'addition',
    service_type: 'generic',
    payer_basis: 'medical',
    provider_scope: 'pharmacy',
    selection_mode: 'manual',
    calculation_unit: 'point',
    display_order: 430,
    name: '服薬情報等提供料2 ハ',
    code: 'MED_INFO_PROVISION_2_HA',
    amount: 20,
    conditions: {
      information_provision_type: '2_ha',
      target: 'care_manager',
      same_month_home_management_disallowed: true,
      frequency_limit: 'monthly_once',
    },
    source_url: MEDICAL_TABLE_URL,
    source_note: '調剤報酬点数表 区分15の5 服薬情報等提供料2 ハ 20点',
  },
  {
    ssot_key: 'medical.information_provision.3',
    rule_type: 'addition',
    service_type: 'generic',
    payer_basis: 'medical',
    provider_scope: 'pharmacy',
    selection_mode: 'manual',
    calculation_unit: 'point',
    display_order: 440,
    name: '服薬情報等提供料3',
    code: 'MED_INFO_PROVISION_3',
    amount: 50,
    conditions: {
      information_provision_type: '3',
      pre_admission_medication_reconciliation: true,
    },
    source_url: MEDICAL_TABLE_URL,
    source_note: '調剤報酬点数表 区分15の5 服薬情報等提供料3 50点',
  },
  {
    ssot_key: 'medical.home_duplicate_interaction.change_other',
    rule_type: 'addition',
    service_type: 'generic',
    payer_basis: 'medical',
    provider_scope: 'pharmacy',
    selection_mode: 'manual',
    calculation_unit: 'point',
    display_order: 450,
    name: '在宅患者重複投薬・相互作用等防止管理料1 イ',
    code: 'MED_HOME_DUPLICATE_CHANGE_OTHER',
    amount: 40,
    conditions: {
      duplicate_interaction_type: '1_i',
      residual_adjustment: false,
      requires_prescription_change: true,
    },
    source_url: MEDICAL_TABLE_URL,
    source_note: '調剤報酬点数表 区分15の6 在宅患者重複投薬・相互作用等防止管理料1 イ 40点',
  },
  {
    ssot_key: 'medical.home_duplicate_interaction.change_residual',
    rule_type: 'addition',
    service_type: 'generic',
    payer_basis: 'medical',
    provider_scope: 'pharmacy',
    selection_mode: 'manual',
    calculation_unit: 'point',
    display_order: 460,
    name: '在宅患者重複投薬・相互作用等防止管理料1 ロ',
    code: 'MED_HOME_DUPLICATE_CHANGE_RESIDUAL',
    amount: 20,
    conditions: {
      duplicate_interaction_type: '1_ro',
      residual_adjustment: true,
      requires_prescription_change: true,
    },
    source_url: MEDICAL_TABLE_URL,
    source_note: '調剤報酬点数表 区分15の6 在宅患者重複投薬・相互作用等防止管理料1 ロ 20点',
  },
  {
    ssot_key: 'medical.home_duplicate_interaction.proposal_other',
    rule_type: 'addition',
    service_type: 'generic',
    payer_basis: 'medical',
    provider_scope: 'pharmacy',
    selection_mode: 'manual',
    calculation_unit: 'point',
    display_order: 470,
    name: '在宅患者重複投薬・相互作用等防止管理料2 イ',
    code: 'MED_HOME_DUPLICATE_PROPOSAL_OTHER',
    amount: 40,
    conditions: {
      duplicate_interaction_type: '2_i',
      residual_adjustment: false,
      proposal_reflected: true,
    },
    source_url: MEDICAL_TABLE_URL,
    source_note: '調剤報酬点数表 区分15の6 在宅患者重複投薬・相互作用等防止管理料2 イ 40点',
  },
  {
    ssot_key: 'medical.home_duplicate_interaction.proposal_residual',
    rule_type: 'addition',
    service_type: 'generic',
    payer_basis: 'medical',
    provider_scope: 'pharmacy',
    selection_mode: 'manual',
    calculation_unit: 'point',
    display_order: 480,
    name: '在宅患者重複投薬・相互作用等防止管理料2 ロ',
    code: 'MED_HOME_DUPLICATE_PROPOSAL_RESIDUAL',
    amount: 20,
    conditions: {
      duplicate_interaction_type: '2_ro',
      residual_adjustment: true,
      proposal_reflected: true,
    },
    source_url: MEDICAL_TABLE_URL,
    source_note: '調剤報酬点数表 区分15の6 在宅患者重複投薬・相互作用等防止管理料2 ロ 20点',
  },
  // ── 在宅中心静脈栄養法加算 ──
  {
    ssot_key: 'medical.addition.central_venous_nutrition',
    rule_type: 'addition',
    service_type: 'medical_home_visit',
    payer_basis: 'medical',
    provider_scope: 'pharmacy',
    selection_mode: 'manual',
    calculation_unit: 'point',
    display_order: 155,
    name: '在宅中心静脈栄養法加算',
    code: 'MED_ADD_CENTRAL_VENOUS',
    amount: 150,
    conditions: {
      requires_central_venous_nutrition: true,
      special_cap_eligible: true,
    },
    source_url: MEDICAL_SOURCE_URL,
    source_note: '調剤報酬点数表 区分15 在宅中心静脈栄養法加算 150点',
  },

  // ── 在宅薬学総合体制加算 ──
  // 薬局ごとの届出状況で適用が異なるため、SSOTルールではなく
  // PharmacySiteBillingConfig (薬局マスター) で管理する。
  // 加算1: 15点 / 加算2: 50点 (施設基準届出要)
  // → billing-evidence.ts の upsertBillingEvidenceForVisit で
  //    PharmacySiteBillingConfig.home_comprehensive_1/2 を参照して
  //    候補を直接生成する。

  // ── 在宅移行初期管理料（令和6年新設） ──
  {
    ssot_key: 'medical.home_transition_initial',
    rule_type: 'addition',
    service_type: 'medical_home_visit',
    payer_basis: 'medical',
    provider_scope: 'pharmacy',
    selection_mode: 'manual',
    calculation_unit: 'point',
    display_order: 200,
    name: '在宅移行初期管理料',
    code: 'MED_HOME_TRANSITION_INITIAL',
    amount: 240,
    conditions: {
      requires_initial_transition: true,
      once_per_patient: true,
    },
    evidence_requirements: {
      requires_physician_instruction: true,
      requires_management_plan: true,
    },
    source_url: MEDICAL_TABLE_URL,
    source_note: '調剤報酬点数表 区分15の8 在宅移行初期管理料 240点（令和6年新設。退院処方後の在宅移行時に1回）',
  },

  // ── 退院時共同指導料 ──
  {
    ssot_key: 'medical.discharge_joint_guidance',
    rule_type: 'addition',
    service_type: 'generic',
    payer_basis: 'medical',
    provider_scope: 'pharmacy',
    selection_mode: 'manual',
    calculation_unit: 'point',
    display_order: 300,
    name: '退院時共同指導料',
    code: 'MED_DISCHARGE_JOINT_GUIDANCE',
    amount: 600,
    conditions: {
      requires_hospital_conference: true,
      once_per_admission: true,
    },
    evidence_requirements: {
      requires_visit_documentation: true, // 退院時カンファレンス参加記録
    },
    source_url: MEDICAL_TABLE_URL,
    source_note: '調剤報酬点数表 区分15の4 退院時共同指導料 600点（入院中の患者1回）',
  },

  // ── 在宅患者緊急時等共同指導料 ──
  {
    ssot_key: 'medical.emergency_joint_guidance',
    rule_type: 'addition',
    service_type: 'medical_home_visit',
    payer_basis: 'medical',
    provider_scope: 'pharmacy',
    selection_mode: 'manual',
    calculation_unit: 'point',
    display_order: 350,
    name: '在宅患者緊急時等共同指導料',
    code: 'MED_EMERGENCY_JOINT_GUIDANCE',
    amount: 700,
    conditions: {
      requires_emergency_conference: true,
      monthly_cap: 2,
    },
    evidence_requirements: {
      requires_visit_documentation: true, // 緊急時カンファレンス参加記録
    },
    source_url: MEDICAL_TABLE_URL,
    source_note: '調剤報酬点数表 区分15の7 在宅患者緊急時等共同指導料 700点（月2回まで）',
  },
  {
    ssot_key: 'medical.addition.terminal_care',
    rule_type: 'addition',
    service_type: 'medical_home_visit',
    payer_basis: 'medical',
    provider_scope: 'pharmacy',
    selection_mode: 'manual',
    calculation_unit: 'point',
    display_order: 360,
    name: '在宅ターミナルケア加算',
    code: 'C013',
    amount: 2500,
    conditions: {
      monthly_cap: 1,
    },
    evidence_requirements: {
      requires_visit_documentation: true,
      requires_written_report: true,
    },
    source_url: MEDICAL_TABLE_URL,
    source_note: '調剤報酬点数表 C013 在宅患者訪問薬剤管理指導料 ターミナルケア加算 2500点',
  },

  // ── 経管投薬支援料 ──
  {
    ssot_key: 'medical.enteral_medication_support',
    rule_type: 'addition',
    service_type: 'generic',
    payer_basis: 'medical',
    provider_scope: 'pharmacy',
    selection_mode: 'manual',
    calculation_unit: 'point',
    display_order: 380,
    name: '経管投薬支援料',
    code: 'MED_ENTERAL_MEDICATION_SUPPORT',
    amount: 100,
    conditions: {
      requires_enteral_feeding: true,
      once_per_patient: true,
    },
    source_url: MEDICAL_TABLE_URL,
    source_note: '調剤報酬点数表 区分14の4 経管投薬支援料 100点（初回のみ）',
  },

  // ── 在宅患者緊急訪問薬剤管理指導料（令和6年度） ──
  // 介護認定の有無に関わらず医療保険で算定。
  // 1: 計画的訪問の対象疾患の急変 500点
  // 2: それ以外の急変 200点
  {
    ssot_key: 'medical.emergency_visit.1',
    rule_type: 'base',
    service_type: 'medical_home_visit',
    payer_basis: 'medical',
    provider_scope: 'pharmacy',
    selection_mode: 'auto',
    calculation_unit: 'point',
    display_order: 500,
    name: '在宅患者緊急訪問薬剤管理指導料1',
    code: 'MED_EMERGENCY_VISIT_1',
    amount: 500,
    conditions: {
      visit_type: 'emergency',
      emergency_category: 'planned_disease_exacerbation',
      monthly_cap: 4,
    },
    evidence_requirements: {
      requires_physician_instruction: true,
      requires_management_plan: true,
      requires_visit_documentation: true,
      requires_written_report: true,
    },
    source_url: MEDICAL_TABLE_URL,
    source_note: '調剤報酬点数表 区分15の3 在宅患者緊急訪問薬剤管理指導料1 500点（計画的訪問の対象疾患の急変）',
  },
  {
    ssot_key: 'medical.emergency_visit.2',
    rule_type: 'base',
    service_type: 'medical_home_visit',
    payer_basis: 'medical',
    provider_scope: 'pharmacy',
    selection_mode: 'auto',
    calculation_unit: 'point',
    display_order: 510,
    name: '在宅患者緊急訪問薬剤管理指導料2',
    code: 'MED_EMERGENCY_VISIT_2',
    amount: 200,
    conditions: {
      visit_type: 'emergency',
      emergency_category: 'other_exacerbation',
      monthly_cap: 4,
    },
    evidence_requirements: {
      requires_physician_instruction: true,
      requires_management_plan: true,
      requires_visit_documentation: true,
      requires_written_report: true,
    },
    exclusion_rules: {
      same_month_exclusive: [
        'MED_HOME_VISIT_SINGLE',
        'MED_HOME_VISIT_MULTI_2_9',
        'MED_HOME_VISIT_MULTI_10_PLUS',
        'CARE_HOME_PHARMACY_SINGLE',
        'CARE_HOME_PHARMACY_MULTI_2_9',
        'CARE_HOME_PHARMACY_MULTI_10_PLUS',
      ],
    },
    source_url: MEDICAL_TABLE_URL,
    source_note: '調剤報酬点数表 区分15の3 在宅患者緊急訪問薬剤管理指導料2 200点（それ以外の急変）',
  },
  {
    ssot_key: 'medical.emergency_visit.online',
    rule_type: 'base',
    service_type: 'medical_home_visit',
    payer_basis: 'medical',
    provider_scope: 'pharmacy',
    selection_mode: 'auto',
    calculation_unit: 'point',
    display_order: 520,
    name: '在宅患者緊急オンライン薬剤管理指導料',
    code: 'MED_EMERGENCY_VISIT_ONLINE',
    amount: 59,
    conditions: {
      visit_type: 'emergency',
      emergency_category: 'online',
      monthly_cap: 4,
    },
    evidence_requirements: {
      requires_physician_instruction: true,
      requires_management_plan: true,
      requires_visit_documentation: true,
      requires_written_report: true,
    },
    source_url: MEDICAL_TABLE_URL,
    source_note: '調剤報酬点数表 区分15の3 在宅患者緊急オンライン薬剤管理指導料 59点',
  },
];
